import type { Drill } from './types'

export const DRILL_REGISTRY: Drill[] = [
  {
    id: 'sink_down_exercise',
    nameEn: 'Sink Down Exercise',
    nameZh: '下沉练习',
    stroke: 'General',
    category: 'Breathing',
    description: '在浅水区练习完整吐气与放松下沉，建立“先呼气再吸气”的呼吸节奏。',
    purpose: ['水下呼气习惯', '放松与水感', '降低紧张导致的抬头'],
    keyPoints: ['脸入水后持续吐泡', '吐气更长更充分', '吸气短而快，立即回到吐气'],
    commonErrors: ['憋气后猛吸', '抬头找空气', '身体僵硬不下沉'],
    suitableLevels: ['L1', 'L2'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升', '耐力发展'],
    recommendedEquipment: [],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 1,
  },
  {
    id: 'breathe_bubble_bubble_breathe',
    nameEn: 'Breathe-Bubble-Bubble-Breathe',
    nameZh: '呼吸-吐泡-吐泡-呼吸',
    stroke: 'Freestyle',
    category: 'Breathing',
    description: '自由泳节奏呼吸练习，建立稳定的水下吐气节奏与换气时机。',
    purpose: ['稳定呼吸节奏', '减少抬头', '建立双侧或规律换气'],
    keyPoints: ['水下持续吐泡', '换气时头随身体滚转', '吸气后立刻回到吐气'],
    commonErrors: ['换气时抬头', '水下不吐气', '换气过晚导致慌乱'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展', '铁人三项专项'],
    recommendedEquipment: [],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'popeye_breathing',
    nameEn: 'Popeye Breathing',
    nameZh: '波派换气',
    stroke: 'Freestyle',
    category: 'Breathing',
    description: '换气时保持一只眼睛在水下，控制头位，减少抬头带来的下沉。',
    purpose: ['降低抬头幅度', '保持身体线条', '提高换气效率'],
    keyPoints: ['一只眼睛仍在水中', '下巴贴近肩膀', '身体滚转带动呼吸'],
    commonErrors: ['两眼都出水', '头先抬后转', '转头导致手臂下压'],
    suitableLevels: ['L1', 'L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'reach_to_inhale',
    nameEn: 'Reach to Inhale',
    nameZh: '伸展换气',
    stroke: 'Freestyle',
    category: 'Breathing',
    description: '换气时保持前伸“长”，减少换气造成的阻力与下沉。',
    purpose: ['换气保持伸展', '减少阻力波动', '稳定节奏'],
    keyPoints: ['换气侧前臂保持伸展', '身体滚转而非抬头', '吸气短促'],
    commonErrors: ['换气时前手下压', '急促抬头', '吸气后不回吐气'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Middle Distance', 'Distance', 'Sprint'],
    goalTypes: ['技术优化', '耐力发展', '成绩提升'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'breathe_from_hips',
    nameEn: 'Breathe from Hips',
    nameZh: '髋部带动换气',
    stroke: 'Freestyle',
    category: 'Rotation',
    description: '强调由髋部与躯干滚转带动换气，避免颈部单独扭转。',
    purpose: ['建立正确滚转', '降低颈肩紧张', '提高呼吸稳定性'],
    keyPoints: ['髋与肩一起滚转', '头随身体转动', '保持前伸线条'],
    commonErrors: ['只扭头不滚转', '滚转过大导致蛇形', '呼吸时下压手臂'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Middle Distance', 'Distance', 'Sprint'],
    goalTypes: ['技术优化', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: ['腰部'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'constant_breathing',
    nameEn: 'Constant Breathing',
    nameZh: '持续呼吸节奏',
    stroke: 'Freestyle',
    category: 'Breathing',
    description: '在较低强度下保持稳定换气频率，强调“全程都在吐气”。',
    purpose: ['耐力游呼吸稳定', '降低憋气', '建立可持续节奏'],
    keyPoints: ['水下持续吐气', '换气频率固定', '保持动作松弛'],
    commonErrors: ['强度一高就憋气', '换气不规律', '抬头导致腿下沉'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Middle Distance', 'Distance'],
    goalTypes: ['耐力发展', '铁人三项专项', '成绩提升'],
    recommendedEquipment: [],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'side_glide_with_breathing',
    nameEn: 'Freestyle Side Glide with Breathing',
    nameZh: '侧滑换气',
    stroke: 'Freestyle',
    category: 'Breathing',
    description: '侧滑漂浮结合换气，强化侧身线条与换气稳定性。',
    purpose: ['侧身线条', '换气稳定', '降低阻力'],
    keyPoints: ['保持侧身平衡', '换气时不抬头', '打腿维持身体位置'],
    commonErrors: ['身体翻回正面', '抬头找空气', '打腿过大导致疲劳'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展'],
    recommendedEquipment: ['浮板', '脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },

  {
    id: 'torpedo_kick',
    nameEn: 'Torpedo Kick',
    nameZh: '鱼雷打腿',
    stroke: 'General',
    category: 'BodyPosition',
    description: '流线抱头打腿，强化身体线条与核心稳定，改善“腿下沉”。',
    purpose: ['身体线条', '核心稳定', '减少阻力'],
    keyPoints: ['抱头流线', '骨盆中立', '小幅快速打腿'],
    commonErrors: ['抬头', '塌腰', '膝盖过度弯曲'],
    suitableLevels: ['L1', 'L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['腰部'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'tip_forward',
    nameEn: 'Tip Forward',
    nameZh: '前倾平衡',
    stroke: 'Freestyle',
    category: 'BodyPosition',
    description: '通过轻微前倾与头位控制，找到“向前下压”的平衡点，减少腿下沉。',
    purpose: ['改善身体平衡', '减少腿下沉', '提高滑行效率'],
    keyPoints: ['头位稳定，目视下方', '胸口轻压水面', '保持身体拉长'],
    commonErrors: ['用力下压导致沉', '抬头', '腰部紧张'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Middle Distance', 'Distance', 'Sprint'],
    goalTypes: ['技术优化', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: ['腰部'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'lateral_balance',
    nameEn: 'Lateral Balance',
    nameZh: '侧向平衡',
    stroke: 'Freestyle',
    category: 'BodyPosition',
    description: '练习侧身漂浮与微打腿保持平衡，建立自由泳侧身线条。',
    purpose: ['侧身稳定', '身体线条', '滚转基础'],
    keyPoints: ['侧身保持一条线', '头位稳定', '髋肩同向'],
    commonErrors: ['身体扭曲', '腿下沉', '打腿过大'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展', '铁人三项专项'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'kick_on_side',
    nameEn: 'Kick On Side',
    nameZh: '侧身打腿',
    stroke: 'Freestyle',
    category: 'BodyPosition',
    description: '侧身打腿强化身体线条与滚转控制，为换气与配合做准备。',
    purpose: ['侧身线条', '滚转控制', '打腿稳定'],
    keyPoints: ['一侧肩髋对齐', '前手伸展', '小幅打腿'],
    commonErrors: ['身体翻回正面', '前手下沉', '踢腿过大'],
    suitableLevels: ['L1', 'L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展', '成绩提升'],
    recommendedEquipment: ['脚蹼', '浮腿夹'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'freestyle_side_glide',
    nameEn: 'Freestyle Side Glide',
    nameZh: '自由泳侧滑',
    stroke: 'Freestyle',
    category: 'BodyPosition',
    description: '强调伸展与侧身滑行，减少每次划水之间的阻力损失。',
    purpose: ['提升滑行效率', '减少阻力', '建立节奏感'],
    keyPoints: ['前伸拉长', '保持侧身', '滚转带动换边'],
    commonErrors: ['滑行过久导致速度掉', '身体摇摆', '抬头影响线条'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Middle Distance', 'Distance', 'Sprint'],
    goalTypes: ['技术优化', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'streamline_freestyle_kick',
    nameEn: 'Streamline Freestyle Kick',
    nameZh: '流线自由泳打腿',
    stroke: 'Freestyle',
    category: 'Kick',
    description: '流线抱头自由泳打腿，强调核心稳定与腿部小幅快频。',
    purpose: ['核心稳定', '腿部节奏', '身体线条'],
    keyPoints: ['抱头流线', '踝关节放松', '从髋带动打腿'],
    commonErrors: ['膝盖打腿', '脚踝僵硬', '塌腰'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['耐力发展', '速度提升', '技术优化'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'one_arm_extended_kick',
    nameEn: 'One-Arm Extended Freestyle Kick',
    nameZh: '单臂前伸打腿',
    stroke: 'Freestyle',
    category: 'Coordination',
    description: '一臂前伸一臂贴体打腿，强调身体平衡与滚转控制。',
    purpose: ['侧身平衡', '滚转控制', '换气基础'],
    keyPoints: ['前伸手保持稳定', '身体保持侧身', '小幅打腿维持线条'],
    commonErrors: ['前手下沉', '腰部摆动', '打腿太大'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展', '铁人三项专项'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },

  {
    id: 'sculling_drills',
    nameEn: 'Sculling Drills',
    nameZh: '划水扫水（Sculling）',
    stroke: 'General',
    category: 'Catch',
    description: '通过小幅扫水寻找对水压力与抱水方向，提升抓水与水感。',
    purpose: ['水感与抱水', '抓水方向', '减少空划'],
    keyPoints: ['前臂与手掌形成受力面', '小幅快速扫水', '保持肘相对更高'],
    commonErrors: ['肘下掉', '扫水幅度过大', '手掌随意拍水'],
    suitableLevels: ['L1', 'L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升', '耐力发展'],
    recommendedEquipment: ['呼吸管', '浮板'],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'fingertip_drag',
    nameEn: 'Fingertip Drag',
    nameZh: '指尖拖拽',
    stroke: 'Freestyle',
    category: 'Recovery',
    description: '高肘恢复练习，改善移臂路径与肩部放松。',
    purpose: ['高肘恢复', '中线控制', '降低肩部压力'],
    keyPoints: ['手指轻触水面', '肘部高于手', '沿身体中线恢复'],
    commonErrors: ['低肘恢复', '手臂外摆'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['技术优化', '成绩提升'],
    recommendedEquipment: [],
    avoidForInjuries: [],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'zipper_drill',
    nameEn: 'Zipper Drill',
    nameZh: '拉链练习',
    stroke: 'Freestyle',
    category: 'Recovery',
    description: '恢复阶段手沿身体侧线“拉拉链”，帮助建立高肘恢复与贴身移臂。',
    purpose: ['高肘恢复', '贴身移臂', '减少外摆'],
    keyPoints: ['拇指沿身体侧线', '肘高于手', '肩部放松'],
    commonErrors: ['手离身体过远', '肩部耸起', '动作僵硬'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升'],
    recommendedEquipment: [],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'shark_fin_drill',
    nameEn: 'Shark Fin Drill',
    nameZh: '鲨鱼鳍练习',
    stroke: 'Freestyle',
    category: 'Rotation',
    description: '在恢复中停顿“鲨鱼鳍”姿势，强化滚转与肘位控制。',
    purpose: ['滚转控制', '高肘恢复', '身体平衡'],
    keyPoints: ['肘指向上方', '身体保持侧身', '停顿时保持线条'],
    commonErrors: ['身体翻正', '肘掉下', '停顿导致速度完全停止'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['技术优化', '成绩提升', '比赛备战'],
    recommendedEquipment: [],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'over_the_barrel',
    nameEn: 'Over the Barrel',
    nameZh: '翻桶抓水',
    stroke: 'Freestyle',
    category: 'Catch',
    description: '模拟“翻过桶”的高肘抱水路径，减少直臂下压。',
    purpose: ['高肘抓水', '抱水路径', '减少前端阻力'],
    keyPoints: ['肘相对更高', '前臂向下“立起”', '保持肩胛稳定'],
    commonErrors: ['直臂下压', '耸肩', '入水过宽'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'three_d_freestyle',
    nameEn: '3D Freestyle',
    nameZh: '3D 自由泳',
    stroke: 'Freestyle',
    category: 'Technique',
    description: '强调抓水、推进、恢复三维协同，避免平面划水与蛇形。',
    purpose: ['推进效率', '动作协调', '保持线条'],
    keyPoints: ['抓水后向后推进', '身体保持稳定', '恢复轻松高肘'],
    commonErrors: ['横向扫水', '身体摆动', '发力断续'],
    suitableLevels: ['L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['成绩提升', '比赛备战', '技术优化'],
    recommendedEquipment: ['Tempo Trainer'],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 4,
  },
  {
    id: 'accelerate_arm_stroke',
    nameEn: 'Accelerate Arm Stroke',
    nameZh: '加速划水',
    stroke: 'Freestyle',
    category: 'Pull',
    description: '强调“后程加速”的划水节奏，提高推进效率与配速控制。',
    purpose: ['划水节奏', '推进效率', '专项配速控制'],
    keyPoints: ['抓水稳定后逐渐加速', '末端推到位', '保持身体稳定'],
    commonErrors: ['全程同速', '末端推不完', '耸肩发力'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['成绩提升', '比赛备战', '速度提升'],
    recommendedEquipment: ['Tempo Trainer', '浮腿夹'],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 4,
  },
  {
    id: 'pocket_drill',
    nameEn: 'Pocket Drill',
    nameZh: '口袋练习',
    stroke: 'Freestyle',
    category: 'Catch',
    description: '在划水后段“触碰口袋”形成更完整的后推路径，减少提前出水。',
    purpose: ['后推完整', '减少漏水', '提高推进效率'],
    keyPoints: ['后推到髋旁', '手掌向后', '身体保持稳定'],
    commonErrors: ['提前出水', '向外扫水', '身体摇摆'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升'],
    recommendedEquipment: [],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'popov_drill',
    nameEn: 'Popov Drill',
    nameZh: '波波夫练习',
    stroke: 'Freestyle',
    category: 'Recovery',
    description: '缩短恢复并保持高质量入水，强调节奏与动作经济性。',
    purpose: ['恢复效率', '节奏控制', '动作经济性'],
    keyPoints: ['恢复贴身放松', '入水在肩前', '保持高划频不乱'],
    commonErrors: ['恢复过快导致乱', '入水过宽', '肩部紧张'],
    suitableLevels: ['L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['比赛备战', '成绩提升', '速度提升'],
    recommendedEquipment: ['Tempo Trainer'],
    avoidForInjuries: ['肩部'],
    source: 'Drill库.md',
    difficulty: 4,
  },
  {
    id: 'broken_arrow_drill',
    nameEn: 'Broken Arrow Drill',
    nameZh: '折箭练习',
    stroke: 'Freestyle',
    category: 'Coordination',
    description: '通过“单侧前伸+交替划水”的配合练习，强化中线控制与滚转节奏。',
    purpose: ['中线控制', '滚转节奏', '减少蛇形'],
    keyPoints: ['前伸手稳定', '划水贴近中线', '滚转由髋带动'],
    commonErrors: ['前伸手漂移', '交替节奏乱', '身体左右摆动'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Middle Distance', 'Distance', 'Sprint'],
    goalTypes: ['技术优化', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: ['腰部'],
    source: 'Drill库.md',
    difficulty: 3,
  },

  {
    id: 'ballet_leg_kick',
    nameEn: 'Ballet Leg Kick Drill',
    nameZh: '芭蕾腿打腿',
    stroke: 'Freestyle',
    category: 'Kick',
    description: '强调从髋部发起打腿，避免膝盖过度弯曲。',
    purpose: ['髋带动打腿', '提高踝部放松', '减少阻力'],
    keyPoints: ['腿长而松', '从髋发力', '脚背放松绷直'],
    commonErrors: ['膝盖打腿', '脚踝僵硬', '踢腿幅度过大'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '速度提升', '耐力发展'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'fish_dont_have_knees',
    nameEn: "Fish Don't Have Knees",
    nameZh: '鱼没有膝盖',
    stroke: 'Freestyle',
    category: 'Kick',
    description: '通过提示语纠正“屈膝打腿”，强化从髋部打腿。',
    purpose: ['纠正屈膝', '提高踝部放松', '节奏打腿'],
    keyPoints: ['髋主导打腿', '膝盖自然微弯', '脚踝放松'],
    commonErrors: ['膝盖大幅屈伸', '脚踝僵硬', '打腿过深'],
    suitableLevels: ['L1', 'L2'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展'],
    recommendedEquipment: ['浮板'],
    avoidForInjuries: ['膝关节'],
    source: 'Drill库.md',
    difficulty: 1,
  },
  {
    id: 'kick_the_ball',
    nameEn: 'Kick the Ball',
    nameZh: '踢球打腿',
    stroke: 'Freestyle',
    category: 'Kick',
    description: '想象脚背轻触“球”，保持小幅快频，避免大幅踢水。',
    purpose: ['小幅快频', '减少阻力', '提高节奏'],
    keyPoints: ['脚背轻触水面', '幅度小频率快', '从髋带动'],
    commonErrors: ['踢水过深', '膝盖过度弯曲', '频率过低'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['速度提升', '成绩提升', '技术优化'],
    recommendedEquipment: ['浮板', '脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'invisible_kickboard',
    nameEn: 'Invisible Kickboard',
    nameZh: '隐形浮板打腿',
    stroke: 'Freestyle',
    category: 'BodyPosition',
    description: '不使用浮板，双臂前伸保持线条，用核心与呼吸控制身体位置。',
    purpose: ['核心稳定', '身体线条', '减少依赖浮板'],
    keyPoints: ['双臂前伸', '头位稳定', '小幅打腿'],
    commonErrors: ['抬头找空气', '腰部塌陷', '打腿过大'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Middle Distance', 'Distance', 'Sprint'],
    goalTypes: ['耐力发展', '技术优化', '铁人三项专项'],
    recommendedEquipment: ['呼吸管'],
    avoidForInjuries: ['腰部'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'two_beat_kick',
    nameEn: 'Two-Beat Kick',
    nameZh: '两次打腿',
    stroke: 'Freestyle',
    category: 'Coordination',
    description: '练习两次打腿节奏，提升动作经济性，常用于长距离与铁三。',
    purpose: ['动作经济性', '长距离节奏', '减少无效腿耗'],
    keyPoints: ['一臂划水配合一次打腿', '保持滚转节奏', '腿幅度小'],
    commonErrors: ['节奏对不上', '腿打太大', '身体左右摆动'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Distance', 'Middle Distance'],
    goalTypes: ['铁人三项专项', '耐力发展', '技术优化'],
    recommendedEquipment: [],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'six_beat_kick',
    nameEn: 'Six-Beat Kick',
    nameZh: '六次打腿',
    stroke: 'Freestyle',
    category: 'Coordination',
    description: '练习六次打腿节奏，提高速度与稳定性，常用于短中距离。',
    purpose: ['提高速度', '身体稳定', '配合节奏'],
    keyPoints: ['每次划水配合三次打腿', '踝放松', '保持核心稳定'],
    commonErrors: ['腿太大导致疲劳', '膝盖打腿', '节奏乱'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['速度提升', '成绩提升', '比赛备战'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'vertical_flutter_kick',
    nameEn: 'Vertical Flutter Kick',
    nameZh: '垂直打腿',
    stroke: 'General',
    category: 'Kick',
    description: '深水垂直打腿，提高腿部力量与踝关节放松，强化速度耐力。',
    purpose: ['腿部力量', '踝关节放松', '速度耐力'],
    keyPoints: ['身体竖直', '小幅快频', '从髋带动'],
    commonErrors: ['身体前倾抱膝', '频率过低', '脚踝僵硬'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance'],
    goalTypes: ['速度提升', '成绩提升'],
    recommendedEquipment: [],
    avoidForInjuries: ['膝关节', '踝关节'],
    source: 'Drill库.md',
    difficulty: 4,
  },

  {
    id: 'six_one_six_drill',
    nameEn: '6-1-6 Drill',
    nameZh: '6-1-6 练习',
    stroke: 'Freestyle',
    category: 'Rotation',
    description: '侧身打腿 6 下 + 1 次划水换边 + 侧身打腿 6 下，强化滚转与配合。',
    purpose: ['滚转控制', '配合节奏', '侧身线条'],
    keyPoints: ['侧身保持稳定', '一次划水完成换边', '换边时保持流线'],
    commonErrors: ['换边乱', '身体翻正', '划水过浅'],
    suitableLevels: ['L1', 'L2', 'L3'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '耐力发展', '铁人三项专项'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 2,
  },
  {
    id: 'six_three_six_drill',
    nameEn: '6-3-6 Drill',
    nameZh: '6-3-6 练习',
    stroke: 'Freestyle',
    category: 'Rotation',
    description: '侧身打腿 6 下 + 3 次划水 + 侧身打腿 6 下，提升滚转与节奏连续性。',
    purpose: ['滚转控制', '节奏连续', '配合稳定'],
    keyPoints: ['三次划水保持节奏', '换边由髋带动', '保持中线控制'],
    commonErrors: ['三次划水变乱', '身体左右摆', '换边抬头'],
    suitableLevels: ['L2', 'L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['技术优化', '成绩提升', '铁人三项专项'],
    recommendedEquipment: ['脚蹼'],
    avoidForInjuries: ['踝关节'],
    source: 'Drill库.md',
    difficulty: 3,
  },
  {
    id: 'power_zone',
    nameEn: 'Power Zone',
    nameZh: '力量区（Power Zone）',
    stroke: 'Freestyle',
    category: 'Rotation',
    description: '强调滚转时的“力量区”发力时机，帮助建立稳定推进与节奏。',
    purpose: ['滚转发力时机', '推进效率', '专项节奏'],
    keyPoints: ['髋驱动滚转', '抓水后进入力量区', '保持身体稳定不蛇形'],
    commonErrors: ['只用手臂硬拉', '滚转不足', '身体摆动'],
    suitableLevels: ['L3', 'L4'],
    eventGroups: ['Sprint', 'Middle Distance', 'Distance'],
    goalTypes: ['成绩提升', '比赛备战', '速度提升'],
    recommendedEquipment: ['Tempo Trainer'],
    avoidForInjuries: ['腰部', '肩部'],
    source: 'Drill库.md',
    difficulty: 4,
  },
]

