/**
 * Pocket Swimming Coach - Drill Registry
 * 自动生成自 Drill库.md
 * 
 * 总计: 260+ Drills
 * 分类: 通用基础 | 自由泳 | 仰泳 | 蛙泳 | 蝶泳 | 转身 | 出发 | 体能训练
 */

import { DrillEntry } from './REGISTRY_SCHEMA';

export const drillRegistry: DrillEntry[] = [

  // ============================================================
  // 1. 通用基础Drill（浮力/流线型/身体位置）
  // ============================================================

  // --- 1.1 漂浮感练习 ---
  
  {
    id: 'drill-float-001',
    name: 'Cannonball Float',
    nameZh: '炮弹式漂浮',
    category: 'float',
    strokes: ['all'],
    level: 'L1',
    purpose: ['水感培养'],
    steps: ['吸气后蜷缩', '下巴收紧', '松手让身体自然上浮'],
    keyPoints: ['感觉身体如何被水支撑', '找到浮心'],
    commonErrors: [{ error: '紧张导致下沉', correction: '放松全身肌肉' }],
    recommendedSets: '3-5次，每次保持30-60秒',
    recommendedZones: ['Z1'],
    progressions: ['Dead Swimmer Float'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['漂浮', '入门', '浮力', '水感'],
  },
  {
    id: 'drill-float-002',
    name: "Dead Swimmer's Float",
    nameZh: '"死亡"漂浮',
    category: 'float',
    strokes: ['all'],
    level: 'L1',
    purpose: ['水感培养', '身体位置'],
    steps: ['全身放松漂浮', '脸朝上或朝下', '手臂和腿完全放松', '感受头部自然下垂与脊柱对齐'],
    keyPoints: ['头部自然下垂与脊柱成直线', '全身完全放松'],
    commonErrors: [{ error: '肌肉紧绷', correction: '有意识地放松每个肌肉群' }],
    recommendedSets: '3-5次，每次保持30-60秒',
    recommendedZones: ['Z1'],
    progressions: ['Streamline Float'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['漂浮', '放松', '水感', '脊柱对齐'],
  },
  {
    id: 'drill-float-003',
    name: 'Streamline Float',
    nameZh: '流线型漂浮',
    category: 'float',
    strokes: ['all'],
    level: 'L1',
    purpose: ['身体位置', '水感培养'],
    steps: ['伸展身体成一直线', '手臂过头紧贴耳朵', '保持手脚、肩膀、臀部、脚跟四点浮于水面'],
    keyPoints: ['保持身体成一直线', '手臂紧贴耳朵', '四点对齐浮于水面'],
    commonErrors: [{ error: '身体弯曲', correction: '收紧核心，想象身体像一根木棍' }],
    recommendedSets: '3-5次，每次保持30-60秒',
    recommendedZones: ['Z1'],
    progressions: ['Gliding in Streamline'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['流线型', '漂浮', '身体位置', '入门'],
  },
  {
    id: 'drill-float-004',
    name: 'Gliding in Streamline',
    nameZh: '流线型滑行',
    category: 'float',
    strokes: ['all'],
    level: 'L1',
    purpose: ['身体位置', '水感培养'],
    steps: ['深吸气', '蹬壁滑行', '全浸入水', '保持流线型姿势'],
    keyPoints: ['全身收紧', '头顶指向池底', '肘伸直', '手臂紧贴耳朵'],
    commonErrors: [{ error: '身体抬起', correction: '压胸，保持头顶向下' }],
    recommendedSets: '6-8次蹬壁滑行，每次尽量滑远',
    recommendedZones: ['Z1'],
    progressions: ['Torpedo Kick'],
    contraindications: [],
    source: 'DrillBook 2E / Swim Smooth',
    tags: ['流线型', '滑行', '蹬壁', '入门'],
  },
  {
    id: 'drill-float-005',
    name: 'Pencil Float',
    nameZh: '铅笔漂浮',
    category: 'float',
    strokes: ['all'],
    level: 'L1',
    purpose: ['水感培养', '身体位置'],
    steps: ['垂直漂浮', '头部向后倾斜快速呼吸', '控制上下浮沉'],
    keyPoints: ['脚在正下方', '头部后仰', '保持垂直姿势'],
    commonErrors: [{ error: '身体摇摆', correction: '收紧核心保持稳定' }],
    recommendedSets: '5-8次，每次保持20-30秒',
    recommendedZones: ['Z1'],
    progressions: ['Pencil Drop'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['漂浮', '垂直漂浮', '水感', '控制'],
  },
  {
    id: 'drill-float-006',
    name: 'Pencil Drop',
    nameZh: '铅笔下降',
    category: 'float',
    strokes: ['all'],
    level: 'L2',
    purpose: ['水感培养', '呼吸技术'],
    steps: ['垂直站立', '慢慢蹲下让水没过头顶', '控制呼气节奏'],
    keyPoints: ['控制呼气节奏', '慢慢下沉', '保持放松'],
    commonErrors: [{ error: '失去控制快速下沉', correction: '缓慢呼气，控制下沉速度' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['下沉', '控制', '呼吸', '水感'],
  },

  // --- 1.2 身体位置练习 ---
  
  {
    id: 'drill-balance-001',
    name: 'Head and Body Position',
    nameZh: '墙上四点对齐',
    category: 'balance',
    strokes: ['all'],
    level: 'L1',
    purpose: ['身体位置', '核心稳定性'],
    steps: ['背靠墙站立', '收紧腹部', '肩胛骨、后脑、臀部、脚跟靠墙'],
    keyPoints: ['四个接触点对齐', '核心收紧', '保持自然呼吸'],
    commonErrors: [{ error: '塌腰', correction: '收紧腹部，将下背部贴墙' }],
    recommendedSets: '3-5次，每次保持30-60秒',
    recommendedZones: ['Z1'],
    progressions: ['Standing Streamline'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['身体位置', '对齐', '核心', '陆上练习'],
  },
  {
    id: 'drill-balance-002',
    name: 'Standing Streamline',
    nameZh: '站立流线型',
    category: 'balance',
    strokes: ['all'],
    level: 'L1',
    purpose: ['身体位置', '核心稳定性'],
    steps: ['站立', '双手过头紧贴耳朵', '手臂伸直', '核心收紧'],
    keyPoints: ['手臂伸直', '核心收紧', '手臂紧贴耳朵'],
    commonErrors: [{ error: '手臂打开', correction: '想象双臂被橡皮筋绑在一起' }],
    recommendedSets: '3-5次，每次保持30秒',
    recommendedZones: ['Z1'],
    progressions: ['在水中做流线型'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['流线型', '陆上练习', '身体位置', '入门'],
  },
  {
    id: 'drill-balance-003',
    name: 'Tip Forward',
    nameZh: '下坡漂/压胸漂移',
    category: 'balance',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['身体位置', '核心稳定性'],
    steps: ['压胸使髋腿上浮', '形成"下坡"正姿势', '保持身体成一直线'],
    keyPoints: ['压胸抬髋', '感觉身体像下坡滑行', '髋部上浮'],
    commonErrors: [{ error: '胸未压导致上坡', correction: '想象胸口压向池底' }],
    recommendedSets: '练习10-15米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['游进中压胸'],
    contraindications: [],
    source: 'Swim Smooth / 100 More Drills',
    tags: ['身体位置', '压胸', '下坡漂', '自由泳'],
  },
  {
    id: 'drill-balance-004',
    name: 'Lateral Balance',
    nameZh: '侧向平衡',
    category: 'balance',
    strokes: ['freestyle', 'backstroke'],
    level: 'L2',
    purpose: ['身体位置', '身体滚动'],
    steps: ['不转头只转体侧倾45°', '感受肩膀-髋部联动', '加入轻柔打腿保持平衡'],
    keyPoints: ['肩膀-髋部联动', '保持45°侧卧', '轻柔打腿'],
    commonErrors: [{ error: '身体倾斜过度', correction: '控制侧倾角度，保持45°' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['Side Glide'],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['平衡', '侧卧', '滚动', '身体位置'],
  },
  {
    id: 'drill-balance-005',
    name: 'Streamline',
    nameZh: '流线型',
    category: 'balance',
    strokes: ['all'],
    level: 'L1',
    purpose: ['身体位置', '核心稳定性'],
    steps: ['手臂过头', '紧贴耳朵', '手尖伸直', '核心收紧'],
    keyPoints: ['像一支利箭', '手臂紧贴耳朵', '核心收紧'],
    commonErrors: [{ error: '手臂打开', correction: '想象手臂被绑在一起' }],
    recommendedSets: '陆上3-5次，水中练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth / 100 More Drills',
    tags: ['流线型', '身体位置', '核心', '入门'],
  },
  {
    id: 'drill-balance-006',
    name: 'Kick On Side',
    nameZh: '侧卧打腿',
    category: 'balance',
    strokes: ['freestyle', 'backstroke'],
    level: 'L2',
    purpose: ['身体位置', '身体滚动', '打腿技术'],
    steps: ['侧卧使用脚蹼打腿', '注意手臂对齐', '保持肩膀-髋部联动'],
    keyPoints: ['手臂与肩膀对齐', '保持侧卧姿势', '髋部转动'],
    commonErrors: [{ error: '身体扭曲', correction: '收紧核心，保持身体成一直线' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['换侧练习'],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['侧卧', '打腿', '滚动', '身体位置'],
  },

  // --- 1.3 呼吸基础练习 ---
  
  {
    id: 'drill-breathing-001',
    name: 'Sink Down Exercise',
    nameZh: '下沉练习',
    category: 'breathing',
    strokes: ['all'],
    level: 'L1',
    purpose: ['呼吸技术', '水感培养'],
    steps: ['放松并下沉到池底', '持续呼气', '使用"breathe-bubble-bubble-breathe"口诀'],
    keyPoints: ['持续呼气', '"breathe-bubble-bubble-breathe"口诀', '完全放松'],
    commonErrors: [{ error: '水中憋气', correction: '始终缓慢均匀呼气' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: ['在深水区练习'],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['呼吸', '呼气', '下沉', '水感'],
  },
  {
    id: 'drill-kick-001',
    name: 'Vertical Flutter Kick',
    nameZh: '垂直踢水',
    category: 'kick',
    strokes: ['all'],
    level: 'L2',
    purpose: ['打腿技术', '核心稳定性'],
    steps: ['站立深水区', '直立踢水', '保持头部以上水面'],
    keyPoints: ['脚踝放松', '膝盖轻微弯曲', '从髋部发力'],
    commonErrors: [{ error: '膝盖弯曲过大', correction: '保持腿部伸直，从髋部驱动' }],
    recommendedSets: '30-60秒一组，3-5组',
    recommendedZones: ['Z2'],
    progressions: ['垂直单腿踢'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '垂直', '核心', '脚踝灵活性'],
  },
  {
    id: 'drill-kick-002',
    name: 'Slow Flutter on Front',
    nameZh: '慢速俯面踢水',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L1',
    purpose: ['打腿技术', '身体位置'],
    steps: ['俯卧水面', '慢速轻轻踢水', '保持身体位置'],
    keyPoints: ['脚跟刚破水面为最佳', '轻柔踢水', '保持流线型'],
    commonErrors: [{ error: '踢水幅度过大', correction: '减小幅度，保持轻柔' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['与划水结合'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '俯卧', '自由泳', '入门'],
  },
  {
    id: 'drill-kick-003',
    name: 'Slow Flutter on Back',
    nameZh: '慢速仰面踢水',
    category: 'kick',
    strokes: ['backstroke'],
    level: 'L1',
    purpose: ['打腿技术', '身体位置'],
    steps: ['仰卧水面', '慢速轻轻踢水', '保持身体位置'],
    keyPoints: ['放松踢水', '感受阻力', '脚踝放松'],
    commonErrors: [{ error: '脚踝僵硬', correction: '放松脚踝，像鞭子一样甩动' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['戴脚蹼延长距离'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '仰卧', '仰泳', '入门'],
  },

  // ============================================================
  // 2. 自由泳Drill
  // ============================================================

  // --- 2.1 呼吸练习 ---
  
  {
    id: 'drill-breathing-002',
    name: 'Breathe-Bubble-Bubble-Breathe',
    nameZh: '呼吸节奏练习',
    category: 'breathing',
    strokes: ['freestyle'],
    level: 'L1',
    purpose: ['呼吸技术', '节奏训练'],
    steps: ['按口诀练习', 'breathe-bubble-bubble-breathe', '保持双侧呼吸节奏'],
    keyPoints: ['双侧呼吸节奏', '持续呼气', '节奏稳定'],
    commonErrors: [{ error: '憋气', correction: '在水中始终保持呼气' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['呼吸', '节奏', '自由泳', '双侧呼吸'],
  },
  {
    id: 'drill-breathing-003',
    name: 'Popeye Breathing',
    nameZh: '大力水手呼吸',
    category: 'breathing',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['呼吸技术'],
    steps: ['转头时保持头低位', '嘴角倾斜如大力水手', '在弓形波凹陷处呼吸'],
    keyPoints: ['嘴角倾斜如Popeye', '保持头低位', '在弓形波凹陷处呼吸'],
    commonErrors: [{ error: '抬头过高', correction: '保持头部低位，只转头不抬头' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['呼吸', '转头', '自由泳', '弓形波'],
  },
  {
    id: 'drill-breathing-004',
    name: 'Reach to Inhale',
    nameZh: '伸手吸气',
    category: 'breathing',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['呼吸技术', '移臂技术'],
    steps: ['伸臂转头同步进行', '伸手同时吸气', '保持身体位置'],
    keyPoints: ['"伸手同时吸气"', '转头与伸臂同步', '保持流线型'],
    commonErrors: [{ error: '转头时不伸手', correction: '练习转头和伸臂的同步时机' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['呼吸', '移臂', '同步', '自由泳'],
  },
  {
    id: 'drill-breathing-005',
    name: 'Breathe from Hips',
    nameZh: '髋驱动转头',
    category: 'breathing',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['呼吸技术', '身体滚动'],
    steps: ['髋部转动带动呼吸', '转头不是主动抬头', '保持头低位'],
    keyPoints: ['"Turn your head away from your arm"', '髋部转动带动', '被动转头'],
    commonErrors: [{ error: '主动抬头', correction: '让髋部转动带动头部' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['呼吸', '髋驱动', '滚动', '自由泳'],
  },
  {
    id: 'drill-breathing-006',
    name: 'Constant Breathing',
    nameZh: '持续呼吸',
    category: 'breathing',
    strokes: ['freestyle'],
    level: 'L1',
    purpose: ['呼吸技术', '节奏训练'],
    steps: ['脸部在水中始终呼气', '不憋气', '保持节奏连贯'],
    keyPoints: ['持续均匀呼气', '不憋气', '节奏稳定'],
    commonErrors: [{ error: '憋气', correction: '始终缓慢呼气' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['双侧呼吸'],
    contraindications: [],
    source: '100 More Drills',
    tags: ['呼吸', '持续呼气', '节奏', '自由泳'],
  },
  {
    id: 'drill-breathing-007',
    name: 'Freestyle Side Glide with Breathing',
    nameZh: '侧身呼吸滑行',
    category: 'breathing',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['呼吸技术', '身体位置'],
    steps: ['侧身滑行', '转头呼吸时髋部保持不动', '保持侧卧姿势'],
    keyPoints: ['保持侧卧姿势', '髋部稳定', '只转头不转髋'],
    commonErrors: [{ error: '转头时髋部移动', correction: '收紧核心，保持髋部稳定' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['练习非惯用侧呼吸'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['呼吸', '侧身', '滑行', '自由泳'],
  },

  // --- 2.2 身体位置练习 ---
  
  {
    id: 'drill-balance-007',
    name: 'Streamline Freestyle Kick, No Breath',
    nameZh: '无呼吸流线型踢水',
    category: 'balance',
    strokes: ['freestyle'],
    level: 'L1',
    purpose: ['身体位置', '打腿技术'],
    steps: ['手臂过头紧贴耳朵', '无呼吸踢水前进', '保持流线型'],
    keyPoints: ['眼睛向下', '后脑贴近水面', '保持流线型'],
    commonErrors: [{ error: '头抬太高', correction: '眼睛向下看池底' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['用脚蹼增加距离'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['流线型', '打腿', '无呼吸', '自由泳'],
  },
  {
    id: 'drill-balance-008',
    name: 'One-Arm Extended Freestyle Kick',
    nameZh: '单臂伸展踢水',
    category: 'balance',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['身体位置', '身体滚动'],
    steps: ['一臂向前伸展', '另一臂放体侧', '踢水前进'],
    keyPoints: ['髋部轻微转动', '保持身体位置', '伸展臂稳定'],
    commonErrors: [{ error: '身体歪斜', correction: '收紧核心，保持身体平衡' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['换臂练习'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '打腿', '身体位置', '自由泳'],
  },
  {
    id: 'drill-kick-004',
    name: 'Torpedo Kick',
    nameZh: '鱼雷打腿',
    category: 'kick',
    strokes: ['freestyle', 'backstroke'],
    level: 'L1',
    purpose: ['打腿技术', '核心稳定性', '身体位置'],
    steps: ['手臂在头顶流线型', '俯卧或仰卧打腿', '核心收紧'],
    keyPoints: ['核心收紧', '从髋部发力', '保持流线型'],
    commonErrors: [{ error: '身体弯曲', correction: '收紧核心，保持身体成一直线' }],
    recommendedSets: '25-50米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['游回时保持流线型'],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['打腿', '流线型', '核心', '鱼雷'],
  },
  {
    id: 'drill-balance-009',
    name: 'Freestyle Side Glide',
    nameZh: '侧身滑行',
    category: 'balance',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['身体位置', '身体滚动'],
    steps: ['侧卧踢水', '理解身体滚动', '保持侧卧姿势'],
    keyPoints: ['肩膀-髋部联动', '保持侧卧姿势', '轻柔打腿'],
    commonErrors: [{ error: '肩髋分离', correction: '保持肩膀和髋部同步转动' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['侧卧换方向'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['侧身', '滑行', '滚动', '自由泳'],
  },
  {
    id: 'drill-kick-005',
    name: 'Ballet Leg Kick Drill',
    nameZh: '芭蕾舞腿打腿',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['打腿技术'],
    steps: ['腿部伸直', '从髋部驱动打腿', '像芭蕾舞腿般伸直'],
    keyPoints: ['从髋部驱动', '腿部完全伸直', '像芭蕾舞腿'],
    commonErrors: [{ error: '膝盖弯曲', correction: '保持腿部伸直，从髋部发力' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['打腿', '芭蕾舞', '髋驱动', '自由泳'],
  },
  {
    id: 'drill-kick-006',
    name: 'Sea Anchors Drill',
    nameZh: '海锚体验',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['打腿技术', '水感培养'],
    steps: ['夹pull buoy', '比较脚尖绷直和90度弯曲的区别', '感受脚踝灵活性影响'],
    keyPoints: ['脚踝灵活性对效率的影响', '感受阻力差异', '脚尖绷直'],
    commonErrors: [{ error: '脚踝僵硬', correction: '放松脚踝，增加灵活性' }],
    recommendedSets: '25-50米对比练习，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['打腿', '脚踝', '灵活性', '对比'],
  },
  {
    id: 'drill-balance-010',
    name: 'No Flat Freestyle',
    nameZh: '避免平板游泳',
    category: 'balance',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['身体位置', '身体滚动'],
    steps: ['身体全程用滚动产生的杠杆力量', '避免平躺', '保持滚动'],
    keyPoints: ['转髋产生力量', '全程滚动', '避免平板'],
    commonErrors: [{ error: '平躺不滚动', correction: '主动转动髋部，保持滚动节奏' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['Lean In/Out'],
    contraindications: [],
    source: '100 More Drills',
    tags: ['滚动', '平板', '杠杆', '自由泳'],
  },

  // --- 2.3 划水技术练习 ---
  
  {
    id: 'drill-catch-001',
    name: 'Sculling Drills',
    nameZh: '划水感知练习',
    category: 'catch',
    strokes: ['freestyle', 'backstroke', 'butterfly'],
    level: 'L2',
    purpose: ['抓水/划水', '水感培养'],
    steps: ['使用pull buoy', '手在水中做"8字"或"S"形划水', '感受水的阻力'],
    keyPoints: ['感受水的阻力', '手掌对水', '轻柔划水'],
    commonErrors: [{ error: '划水太快', correction: '放慢速度，感受水的阻力' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['闭眼练习'],
    contraindications: [],
    source: 'Swim Smooth / DrillBook 2E',
    tags: ['划水', '水感', '抓水', '感知'],
  },
  {
    id: 'drill-recovery-001',
    name: 'Fingertip Drag',
    nameZh: '指尖拖拽',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术', '核心稳定性'],
    steps: ['高肘抬臂', '手指拖过身体', '手指出水后贴近身体拖拽'],
    keyPoints: ['手指贴近身体中线', '高肘移臂', '放松手腕'],
    commonErrors: [{ error: '手臂外摆', correction: '保持手指贴近身体中线拖拽' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['Loose Hand Swing'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['移臂', '高肘', '指尖', '自由泳'],
  },
  {
    id: 'drill-catch-002',
    name: 'Zipper Drill',
    nameZh: '拉链练习',
    category: 'catch',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['抓水/划水', '移臂技术'],
    steps: ['划水时手掌贴近身体中线', '模拟"拉链"路径', '保持高肘'],
    keyPoints: ['中线对齐', '拉链路径', '高肘'],
    commonErrors: [{ error: '划水外扫', correction: '保持手掌贴近身体中线' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划水', '中线', '拉链', '自由泳'],
  },
  {
    id: 'drill-recovery-002',
    name: 'Shark Fin Drill',
    nameZh: '鳍鲨练习',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['划水时手臂出水高度控制', '肘部高于手', '保持高肘移臂'],
    keyPoints: ['肘高于手', '控制高度', '高肘移臂'],
    commonErrors: [{ error: '肘过低', correction: '主动抬肘，保持肘部高于手' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['移臂', '高肘', '鲨鱼鳍', '自由泳'],
  },
  {
    id: 'drill-catch-003',
    name: 'Over the Barrel',
    nameZh: '桶式练习/高肘入水',
    category: 'catch',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['抓水/划水', '移臂技术'],
    steps: ['手过高"桶"形路径入水', '保持高肘', '手入水后在肩宽范围内'],
    keyPoints: ['手入水后在肩宽范围内', '高肘入水', '桶形路径'],
    commonErrors: [{ error: '手入水太宽', correction: '保持手在肩宽范围内入水' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['抓水', '高肘', '入水', '自由泳'],
  },
  {
    id: 'drill-catch-004',
    name: '3D Freestyle',
    nameZh: '三维自由泳',
    category: 'catch',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['抓水/划水'],
    steps: ['水平面上从宽到窄', '垂直面上从前往后', '从深到浅', '三维划水路径'],
    keyPoints: ['三维路径', '水平+垂直+深度', '加速推水'],
    commonErrors: [{ error: '平直划水', correction: '想象三维路径，从宽到窄、从前往后、从深到浅' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加速推水'],
    contraindications: [],
    source: '100 More Drills',
    tags: ['划水', '三维', '路径', '自由泳'],
  },
  {
    id: 'drill-catch-005',
    name: 'Accelerate Arm Stroke',
    nameZh: '加速推水',
    category: 'catch',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['抓水/划水'],
    steps: ['推水段加速', '全程加速', '不停顿'],
    keyPoints: ['全程加速', '推水阶段最快', '不停顿'],
    commonErrors: [{ error: '减速', correction: '保持加速，推水阶段用力' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['划水', '加速', '推水', '自由泳'],
  },
  {
    id: 'drill-recovery-003',
    name: 'Pocket Drill',
    nameZh: '口袋出手机制',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['拇指沿身体向上滑到腋窝', '手的"口袋"机制', '手从口袋滑出'],
    keyPoints: ['up-down-up-and-through节奏', '拇指滑行', '口袋机制'],
    commonErrors: [{ error: '手先出', correction: '让拇指先滑行，肘带动手' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth / 100 More Drills',
    tags: ['移臂', '口袋', '拇指', '自由泳'],
  },
  {
    id: 'drill-recovery-004',
    name: 'Broken Arrow Drill',
    nameZh: '断箭练习',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['手臂垂直后弯曲肘部', '弯曲至少90°', '适合肩部紧张者'],
    keyPoints: ['放松肩部和上背部', '弯曲肘部', '适合肩部紧张者'],
    commonErrors: [{ error: '肩部紧张', correction: '主动放松肩部和上背部' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'Swim Smooth',
    tags: ['移臂', '断箭', '肩部放松', '自由泳'],
  },
  {
    id: 'drill-recovery-005',
    name: 'Popov Drill',
    nameZh: '波波夫练习',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['移臂技术'],
    steps: ['拇指沿身体向上滑到腋窝', 'up-down-up-and-through节奏', '高肘移臂'],
    keyPoints: ['up-down-up-and-through节奏帮助高肘移臂', '以俄罗斯奥运冠军命名', '高肘移臂'],
    commonErrors: [{ error: '肘过低', correction: '保持高肘，拇指滑行引导' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['移臂', '高肘', '波波夫', '自由泳'],
  },
  {
    id: 'drill-recovery-006',
    name: 'Trailing Hand',
    nameZh: '手掌放松跟随',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['手在肘后摆动', '手在肘后放松跟随', '保持放松'],
    keyPoints: ['手放松', '在肘后跟随', '放松甩动'],
    commonErrors: [{ error: '手过于紧张', correction: '完全放松手掌，让其自然跟随' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['移臂', '放松', '跟随', '自由泳'],
  },
  {
    id: 'drill-recovery-007',
    name: 'Loose Hand Swing',
    nameZh: '高肘甩手',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['肘指天', '手松弛', '高肘移臂'],
    keyPoints: ['放松甩手', '肘指天', '手松弛'],
    commonErrors: [{ error: '肘过低', correction: '主动抬肘指向天空' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['移臂', '高肘', '甩手', '自由泳'],
  },

  // --- 2.4 打腿练习 ---
  
  {
    id: 'drill-kick-007',
    name: "Fish don't Have Knees",
    nameZh: '鱼无膝',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['全程像鱼尾流畅', '无关节弯曲', '脚踝驱动'],
    keyPoints: ['脚踝驱动', '膝盖放松', '像鱼尾流畅'],
    commonErrors: [{ error: '膝盖弯曲', correction: '放松膝盖，从髋部和脚踝驱动' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['打腿', '流畅', '鱼尾', '自由泳'],
  },
  {
    id: 'drill-kick-008',
    name: 'Kick the Ball',
    nameZh: '踢球打腿',
    category: 'kick',
    strokes: ['freestyle', 'backstroke'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['想象踢球', '前后各一半幅度', '控制踢水幅度'],
    keyPoints: ['约15英寸（38cm）踢幅', '前后各一半', '控制幅度'],
    commonErrors: [{ error: '幅度过大或过小', correction: '保持约38cm的踢水幅度' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['打腿', '幅度', '踢球', '控制'],
  },
  {
    id: 'drill-kick-009',
    name: 'Invisible Kickboard',
    nameZh: '无板打腿',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['打腿技术', '身体位置'],
    steps: ['徒手打腿', '踝快速', '不依赖板'],
    keyPoints: ['踝快速踢水', '有效打腿', '不依赖板'],
    commonErrors: [{ error: '依赖板', correction: '练习不拿板打腿，感受身体位置' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加入划水'],
    contraindications: [],
    source: '100 More Drills',
    tags: ['打腿', '无板', '脚踝', '自由泳'],
  },
  {
    id: 'drill-kick-010',
    name: 'Two-Beat Kick',
    nameZh: '两拍打腿',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['打腿技术', '节奏训练'],
    steps: ['每划一次腿', '下打对应对侧手入水', '连接手臂和腿部'],
    keyPoints: ['连接手臂和腿部', '对侧协调', '每划一次踢一次'],
    commonErrors: [{ error: '不协调', correction: '练习下打与对侧手入水同步' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['六拍打腿转换'],
    contraindications: [],
    source: 'Swimming Tech',
    tags: ['打腿', '两拍', '节奏', '协调'],
  },
  {
    id: 'drill-kick-011',
    name: 'Six-Beat Kick',
    nameZh: '六拍打腿',
    category: 'kick',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['打腿技术', '节奏训练'],
    steps: ['每划臂一次踢6次腿', '连续轻拍打腿', '计时到抱水和推水点'],
    keyPoints: ['连续轻拍', '每划臂一次踢6次', '节奏稳定'],
    commonErrors: [{ error: '节奏混乱', correction: '数1-2-3-1-2-3保持节奏' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['两拍打腿转换'],
    contraindications: [],
    source: 'Swim Smooth / Swimming Tech',
    tags: ['打腿', '六拍', '节奏', '连续'],
  },
  {
    id: 'drill-kick-012',
    name: 'Mermaid Dolphin Kick',
    nameZh: '美人鱼海豚踢',
    category: 'kick',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['俯卧水面做海豚踢', '从髋部发力', '全身波浪'],
    keyPoints: ['从髋部发力', '波浪传导', '全身协调'],
    commonErrors: [{ error: '从膝盖发力', correction: '从髋部和核心发力，膝盖放松' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['单腿版本'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['海豚踢', '美人鱼', '波浪', '蝶泳'],
  },

  // --- 2.5 移臂与恢复练习 ---
  
  {
    id: 'drill-recovery-008',
    name: 'Shoulder Tap Drill',
    nameZh: '拍肩练习',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['使用脚蹼', '入水前拍肩膀', '确保指尖先入水'],
    keyPoints: ['指尖先入水', '入水前拍肩', '控制入水'],
    commonErrors: [{ error: '拇指先入水', correction: '确保指尖先入水，不是拇指' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['移臂', '入水', '指尖', '自由泳'],
  },
  {
    id: 'drill-recovery-009',
    name: 'Middle Finger Visualization',
    nameZh: '中指专注',
    category: 'recovery',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['入水时中指像枪管一样直指前方', '专注入水方向', '保持流线型'],
    keyPoints: ['中指朝前', '直指前方', '专注方向'],
    commonErrors: [{ error: '入水方向偏移', correction: '想象中指像枪管指向前方目标' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['移臂', '入水', '方向', '专注'],
  },
  {
    id: 'drill-stroke-001',
    name: 'Controlled One-Arm Freestyle',
    nameZh: '控制单臂自由泳',
    category: 'stroke',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['抓水/划水', '身体位置'],
    steps: ['伸展非划水臂', '单臂划水', '控制节奏和身体位置'],
    keyPoints: ['身体位置稳定', '单臂连续划水', '控制节奏'],
    commonErrors: [{ error: '身体左右摇摆', correction: '收紧核心，保持身体稳定' }],
    recommendedSets: '每臂25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '划水', '控制', '自由泳'],
  },
  {
    id: 'drill-stroke-002',
    name: 'Three-Count Switch Freestyle',
    nameZh: '三拍切换自由泳',
    category: 'stroke',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['身体位置', '节奏训练'],
    steps: ['侧卧打腿6次', '1次划水换边', '保持姿势'],
    keyPoints: ['保持姿势', '6次打腿', '1次划水换边'],
    commonErrors: [{ error: '转换中断', correction: '保持动作流畅，不中断' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸版本'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['切换', '打腿', '节奏', '自由泳'],
  },
  {
    id: 'drill-stroke-003',
    name: 'Continuous One-Arm Freestyle',
    nameZh: '连续单臂自由泳',
    category: 'stroke',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['持续单臂划水', '交替手臂', '保持节奏稳定'],
    keyPoints: ['节奏稳定', '连续划水', '交替手臂'],
    commonErrors: [{ error: '节奏混乱', correction: '保持稳定的划水节奏' }],
    recommendedSets: '每臂25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '连续', '节奏', '自由泳'],
  },
  {
    id: 'drill-stroke-004',
    name: 'Continuous Two-Arm Freestyle',
    nameZh: '连续双臂自由泳',
    category: 'stroke',
    strokes: ['freestyle'],
    level: 'L1',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['持续双臂划水', '保持连贯', '不停顿'],
    keyPoints: ['保持连贯', '不停顿', '节奏稳定'],
    commonErrors: [{ error: '停顿', correction: '保持动作连续，不中断' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加速'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['双臂', '连续', '节奏', '自由泳'],
  },
  {
    id: 'drill-stroke-005',
    name: 'Windmill Drill',
    nameZh: '风车练习',
    category: 'stroke',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['双臂交替如风车', '专注连贯节奏', '保持节奏均匀'],
    keyPoints: ['连贯节奏', '风车动作', '节奏均匀'],
    commonErrors: [{ error: '节奏不均', correction: '保持左右臂节奏一致' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加速'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['风车', '节奏', '连贯', '自由泳'],
  },

  // --- 2.6 旋转练习 ---
  
  {
    id: 'drill-rotation-001',
    name: '6-1-6 Drill',
    nameZh: '6-1-6练习',
    category: 'rotation',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['身体滚动', '身体位置'],
    steps: ['侧卧打腿6次', '1次划水', '换边'],
    keyPoints: ['保持姿势', '6次打腿', '1次划水换边'],
    commonErrors: [{ error: '身体下沉', correction: '保持头部位置，收紧核心' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['6-3-6版本'],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['滚动', '打腿', '侧卧', '自由泳'],
  },
  {
    id: 'drill-rotation-002',
    name: '6-3-6 Drill',
    nameZh: '6-3-6练习',
    category: 'rotation',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['身体滚动', '抓水/划水'],
    steps: ['侧卧打腿6次', '3次完整划水', '换边'],
    keyPoints: ['保持姿势', '3次完整划水', '侧卧打腿6次'],
    commonErrors: [{ error: '动作脱节', correction: '保持动作流畅连贯' }],
    recommendedSets: '50-100米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['滚动', '划水', '侧卧', '自由泳'],
  },
  {
    id: 'drill-rotation-003',
    name: 'Power Zone',
    nameZh: '核心发力',
    category: 'rotation',
    strokes: ['freestyle'],
    level: 'L3',
    purpose: ['身体滚动', '核心稳定性'],
    steps: ['坐姿/站姿模拟核心甩动', '肩髋绕轴同步前后甩', '从核心协调身体'],
    keyPoints: ['从核心协调身体', '肩髋同步', '绕轴旋转'],
    commonErrors: [{ error: '只用手臂', correction: '从核心发力，带动肩髋旋转' }],
    recommendedSets: '陆上练习10-15次，水中练习50-100米',
    recommendedZones: ['Z1'],
    progressions: ['在水中练习'],
    contraindications: [],
    source: '100 More Drills',
    tags: ['核心', '滚动', '发力', '旋转'],
  },

  // ============================================================
  // 3. 仰泳Drill
  // ============================================================

  {
    id: 'drill-kick-013',
    name: 'Streamline Back Flutter Kick',
    nameZh: '仰卧流线型踢水',
    category: 'kick',
    strokes: ['backstroke'],
    level: 'L1',
    purpose: ['打腿技术', '身体位置'],
    steps: ['仰卧流线型踢水', '脚跟刚破水面', '保持流线型'],
    keyPoints: ['脚跟刚破水面', '仰卧姿势', '保持流线型'],
    commonErrors: [{ error: '踢水幅度过大', correction: '减小幅度，保持轻柔' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加划水'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '仰卧', '流线型', '仰泳'],
  },
  {
    id: 'drill-balance-011',
    name: 'Backstroke Side Glide',
    nameZh: '仰泳侧滑',
    category: 'balance',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['身体位置', '身体滚动'],
    steps: ['身体侧卧水下踢水', '肩膀-髋部对齐', '保持侧卧姿势'],
    keyPoints: ['肩膀-髋部对齐', '侧卧姿势', '轻柔踢水'],
    commonErrors: [{ error: '身体歪斜', correction: '收紧核心，保持身体成一直线' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加划水'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['侧滑', '仰泳', '滚动', '身体位置'],
  },
  {
    id: 'drill-kick-014',
    name: 'One-Arm Extended Back Kick',
    nameZh: '单臂伸展仰泳踢',
    category: 'kick',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['打腿技术', '身体位置'],
    steps: ['一臂向前伸展', '踢水前进', '髋部稳定'],
    keyPoints: ['髋部稳定', '单臂伸展', '保持平衡'],
    commonErrors: [{ error: '身体旋转过度', correction: '收紧核心，控制旋转幅度' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['换臂'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '单臂', '仰泳', '平衡'],
  },
  {
    id: 'drill-rotation-004',
    name: 'Shoulder Roll Back Kick',
    nameZh: '肩部滚动仰泳踢',
    category: 'rotation',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['身体滚动', '打腿技术'],
    steps: ['肩膀滚动带动踢水', '滚动发力', '保持节奏'],
    keyPoints: ['滚动发力', '肩部带动', '节奏稳定'],
    commonErrors: [{ error: '肩膀不滚动', correction: '主动转动肩膀，带动身体' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['滚动', '仰泳', '肩部', '打腿'],
  },
  {
    id: 'drill-kick-015',
    name: 'Lateral Backstroke Kick',
    nameZh: '侧向仰泳踢',
    category: 'kick',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['打腿技术', '身体位置'],
    steps: ['身体侧位踢水', '控制平衡', '保持侧位'],
    keyPoints: ['控制平衡', '侧位踢水', '保持稳定'],
    commonErrors: [{ error: '身体翻转', correction: '收紧核心，保持侧位' }],
    recommendedSets: '每侧25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '侧向', '仰泳', '平衡'],
  },
  {
    id: 'drill-recovery-010',
    name: 'Backstroke Recovery on Deck',
    nameZh: '岸上仰泳划臂',
    category: 'recovery',
    strokes: ['backstroke'],
    level: 'L1',
    purpose: ['移臂技术'],
    steps: ['站立练习仰泳划臂动作', '小指先入水', '控制路径'],
    keyPoints: ['小指先入水', '高肘恢复', '控制路径'],
    commonErrors: [{ error: '拇指先入', correction: '旋转手臂，小指先入水' }],
    recommendedSets: '陆上练习15-20次，重复3-5组',
    recommendedZones: ['Z1'],
    progressions: ['水中练习'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['移臂', '仰泳', '陆上', '小指'],
  },
  {
    id: 'drill-stroke-006',
    name: 'Streamline Backstroke Single-Arm',
    nameZh: '流线型单臂仰泳',
    category: 'stroke',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['抓水/划水', '身体位置'],
    steps: ['流线型姿势下单臂划水', '注意划水路线', '保持身体稳定'],
    keyPoints: ['划水路线', '身体稳定', '单臂划水'],
    commonErrors: [{ error: '划水过宽', correction: '保持划水路线在身体范围内' }],
    recommendedSets: '每臂25米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '仰泳', '流线型', '划水'],
  },
  {
    id: 'drill-stroke-007',
    name: 'Backstroke L Drill',
    nameZh: '仰泳L型练习',
    category: 'stroke',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['抓水/划水'],
    steps: ['划水路径呈"L"形', '注意划水节奏', '保持身体稳定'],
    keyPoints: ['划水节奏', 'L形路径', '身体稳定'],
    commonErrors: [{ error: '路径不正确', correction: '想象L形路径，保持节奏' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['连续'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划水', '仰泳', 'L型', '路径'],
  },
  {
    id: 'drill-stroke-008',
    name: 'Double-Arm Backstroke',
    nameZh: '双臂仰泳',
    category: 'stroke',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['抓水/划水', '核心稳定性'],
    steps: ['双臂同时划水', '保持身体稳定', '注意节奏'],
    keyPoints: ['身体稳定', '双臂同步', '节奏稳定'],
    commonErrors: [{ error: '失去平衡', correction: '收紧核心，保持身体稳定' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加速'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['双臂', '仰泳', '同步', '平衡'],
  },
  {
    id: 'drill-breathing-008',
    name: 'Backstroke with Breath',
    nameZh: '带呼吸仰泳',
    category: 'breathing',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['呼吸技术'],
    steps: ['肩出水时吸气', '入水时呼气', '找"呼吸袋"时机'],
    keyPoints: ['找"呼吸袋"时机', '肩出水吸气', '节奏稳定'],
    commonErrors: [{ error: '呼吸不协调', correction: '与肩部动作配合呼吸' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['呼吸', '仰泳', '节奏', '配合'],
  },
  {
    id: 'drill-stroke-009',
    name: 'Continuous One-Arm Backstroke',
    nameZh: '连续单臂仰泳',
    category: 'stroke',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['持续单臂划水交替', '保持节奏稳定', '不停顿'],
    keyPoints: ['节奏稳定', '连续划水', '交替手臂'],
    commonErrors: [{ error: '停顿', correction: '保持动作连续流畅' }],
    recommendedSets: '每臂25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '连续', '仰泳', '节奏'],
  },
  {
    id: 'drill-stroke-010',
    name: 'Continuous Two-Arm Backstroke',
    nameZh: '连续双臂仰泳',
    category: 'stroke',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['双臂交替连续', '保持连贯', '节奏稳定'],
    keyPoints: ['连贯', '双臂交替', '节奏稳定'],
    commonErrors: [{ error: '节奏混乱', correction: '保持稳定的交替节奏' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加速'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['双臂', '连续', '仰泳', '节奏'],
  },
  {
    id: 'drill-balance-012',
    name: 'Spine Line',
    nameZh: '脊椎线',
    category: 'balance',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['身体位置', '核心稳定性'],
    steps: ['收紧腹肌成"香蕉位"', '保持脊椎成弧形', '水面在耳后'],
    keyPoints: ['收紧腹肌', '脊椎成弧形', '水面在耳后'],
    commonErrors: [{ error: '塌腰', correction: '收紧腹部，保持弧形' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['脊椎', '仰泳', '核心', '香蕉位'],
  },
  {
    id: 'drill-balance-013',
    name: 'Head on a Pillow',
    nameZh: '头靠水枕',
    category: 'balance',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['身体位置'],
    steps: ['头保持稳定如靠水枕头', '头的独立位置', '不随身体转动'],
    keyPoints: ['独立头部', '稳定如枕', '不随身体'],
    commonErrors: [{ error: '头随身体', correction: '保持头部独立稳定' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['头部', '仰泳', '稳定', '独立'],
  },
  {
    id: 'drill-balance-014',
    name: 'Cup on Forehead',
    nameZh: '头顶水杯',
    category: 'balance',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['身体位置'],
    steps: ['头顶水杯不洒', '头稳定', '保持平衡'],
    keyPoints: ['头稳定', '平衡控制', '不晃动'],
    commonErrors: [{ error: '头晃动', correction: '收紧颈部，保持头部稳定' }],
    recommendedSets: '25-50米，重复2-3次（可用水杯或想象）',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['头部', '仰泳', '稳定', '平衡'],
  },
  {
    id: 'drill-kick-016',
    name: 'Boiling Water',
    nameZh: '沸腾水',
    category: 'kick',
    strokes: ['backstroke'],
    level: 'L3',
    purpose: ['打腿技术'],
    steps: ['用力踢腿让水面沸腾', '充分踢水', '增加幅度'],
    keyPoints: ['充分踢水', '水面沸腾', '用力踢腿'],
    commonErrors: [{ error: '无力', correction: '增加踢水力量和幅度' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z2'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['打腿', '仰泳', '力量', '幅度'],
  },
  {
    id: 'drill-kick-017',
    name: 'Pigeon Toed Kick',
    nameZh: '内扣脚Kick',
    category: 'kick',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['双脚微内扣踢水', '增大踢水面积', '保持节奏'],
    keyPoints: ['增大面积', '双脚微内扣', '节奏稳定'],
    commonErrors: [{ error: '外八字', correction: '脚尖微内扣，增加对水面积' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['打腿', '仰泳', '内扣', '面积'],
  },
  {
    id: 'drill-recovery-011',
    name: 'Up and Over',
    nameZh: '高肘上翻',
    category: 'recovery',
    strokes: ['backstroke'],
    level: 'L3',
    purpose: ['移臂技术'],
    steps: ['肘高"上翻"路径入水', '仰泳高肘恢复', '控制路径'],
    keyPoints: ['高肘恢复', '上翻路径', '肘高于手'],
    commonErrors: [{ error: '肘过低', correction: '保持高肘，上翻入水' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['移臂', '仰泳', '高肘', '上翻'],
  },
  {
    id: 'drill-recovery-012',
    name: 'Locked Elbow Recovery',
    nameZh: '锁定肘恢复',
    category: 'recovery',
    strokes: ['backstroke'],
    level: 'L3',
    purpose: ['移臂技术'],
    steps: ['肘部锁定恢复', '精确对齐', '保持直线'],
    keyPoints: ['精确对齐', '肘部锁定', '保持直线'],
    commonErrors: [{ error: '肘摆动', correction: '锁定肘部，保持稳定' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['移臂', '仰泳', '锁定', '对齐'],
  },

  // ============================================================
  // 4. 蛙泳Drill
  // ============================================================

  {
    id: 'drill-catch-006',
    name: 'Standing Breaststroke Pulling Action',
    nameZh: '站立蛙泳划臂',
    category: 'catch',
    strokes: ['breaststroke'],
    level: 'L1',
    purpose: ['抓水/划水'],
    steps: ['站在水中练习划臂', '注意划臂路线', '控制幅度'],
    keyPoints: ['划臂路线', '控制幅度', '身体稳定'],
    commonErrors: [{ error: '划臂过宽', correction: '保持划臂在肩宽范围内' }],
    recommendedSets: '陆上或浅水练习15-20次，重复3-5组',
    recommendedZones: ['Z1'],
    progressions: ['水中'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划臂', '蛙泳', '站立', '路线'],
  },
  {
    id: 'drill-catch-007',
    name: 'Vertical Breaststroke Pull',
    nameZh: '垂直蛙泳划臂',
    category: 'catch',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['抓水/划水'],
    steps: ['深水中垂直划臂', '注意划臂节奏', '保持垂直'],
    keyPoints: ['划臂节奏', '保持垂直', '动作连贯'],
    commonErrors: [{ error: '动作脱节', correction: '保持动作流畅连贯' }],
    recommendedSets: '30-60秒一组，3-5组',
    recommendedZones: ['Z2'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划臂', '蛙泳', '垂直', '节奏'],
  },
  {
    id: 'drill-catch-008',
    name: 'Quick Hands Breaststroke',
    nameZh: '快速手部蛙泳',
    category: 'catch',
    strokes: ['breaststroke'],
    level: 'L3',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['快速划臂', '保持节奏', '配合踢腿'],
    keyPoints: ['手部快节奏', '快速划臂', '节奏稳定'],
    commonErrors: [{ error: '慢', correction: '加快手部动作，保持节奏' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['配合踢腿'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划臂', '蛙泳', '快速', '节奏'],
  },
  {
    id: 'drill-stroke-011',
    name: 'Pull, Breathe, Kick, Glide',
    nameZh: '划-呼-踢-滑',
    category: 'stroke',
    strokes: ['breaststroke'],
    level: 'L1',
    purpose: ['节奏训练'],
    steps: ['划臂→呼吸→踢腿→滑行', '分离四个动作', '保持节奏'],
    keyPoints: ['节奏分离', '四个动作分明', '滑行充分'],
    commonErrors: [{ error: '同时做', correction: '分离动作，逐一完成' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加速节奏'],
    contraindications: [],
    source: 'DrillBook 2E / Swim Smooth',
    tags: ['节奏', '蛙泳', '分离', '滑行'],
  },
  {
    id: 'drill-stroke-012',
    name: 'Double Glide Breaststroke',
    nameZh: '双滑蛙泳',
    category: 'stroke',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['节奏训练'],
    steps: ['划臂滑行', '踢腿滑行', '两次滑行节奏'],
    keyPoints: ['时机感', '两次滑行', '节奏稳定'],
    commonErrors: [{ error: '滑行太短/太长', correction: '保持适当的滑行时间' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['滑行', '蛙泳', '节奏', '时机'],
  },
  {
    id: 'drill-kick-018',
    name: 'Inverted Breaststroke Kick',
    nameZh: '倒置蛙泳踢',
    category: 'kick',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['俯卧水中练习蹬腿', '膝盖同肩宽', '脚踝旋转'],
    keyPoints: ['膝盖同肩宽', '脚踝旋转', '蹬腿充分'],
    commonErrors: [{ error: '膝盖太宽', correction: '保持膝盖与肩同宽' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['正置'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '蛙泳', '蹬腿', '膝盖'],
  },
  {
    id: 'drill-kick-019',
    name: 'Streamline Breaststroke Kick',
    nameZh: '流线型蛙泳踢',
    category: 'kick',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['打腿技术', '身体位置'],
    steps: ['流线型姿势蹬腿前进', '脚踝旋转全范围', '保持流线型'],
    keyPoints: ['脚踝旋转全范围', '保持流线型', '蹬腿充分'],
    commonErrors: [{ error: '脚踝不转', correction: '主动旋转脚踝，全范围蹬腿' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['打腿', '蛙泳', '流线型', '脚踝'],
  },
  {
    id: 'drill-stroke-013',
    name: 'Controlled Breaststroke',
    nameZh: '控制蛙泳',
    category: 'stroke',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['节奏训练'],
    steps: ['控制每个动作时机', '节奏稳定', '不匆忙'],
    keyPoints: ['节奏稳定', '控制时机', '不匆忙'],
    commonErrors: [{ error: '过快', correction: '放慢节奏，控制每个动作' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['节奏', '蛙泳', '控制', '时机'],
  },
  {
    id: 'drill-stroke-014',
    name: 'Two Kicks to One Pull',
    nameZh: '两踢一划',
    category: 'stroke',
    strokes: ['breaststroke'],
    level: 'L3',
    purpose: ['节奏训练', '打腿技术'],
    steps: ['两次踢腿接一次划臂', '保持协调', '节奏稳定'],
    keyPoints: ['协调', '两次踢腿', '一次划臂'],
    commonErrors: [{ error: '不匹配', correction: '保持两次踢腿对应一次划臂' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['节奏', '蛙泳', '两踢一划', '协调'],
  },
  {
    id: 'drill-stroke-015',
    name: 'Breaststroke Pull with Dolphin Kick',
    nameZh: '划臂+海豚踢',
    category: 'stroke',
    strokes: ['breaststroke'],
    level: 'L3',
    purpose: ['节奏训练', '打腿技术'],
    steps: ['划臂配合海豚踢', '注意时机', '保持协调'],
    keyPoints: ['时机', '协调', '海豚踢配合'],
    commonErrors: [{ error: '不协调', correction: '练习划臂与海豚踢的配合时机' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['蛙泳', '海豚踢', '配合', '时机'],
  },
  {
    id: 'drill-catch-009',
    name: 'Over the Barrel Breaststroke',
    nameZh: '桶式蛙泳',
    category: 'catch',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['抓水/划水'],
    steps: ['手过高"桶"形路径', '高肘划水', '控制入水'],
    keyPoints: ['高肘', '桶形路径', '控制入水'],
    commonErrors: [{ error: '低肘', correction: '保持高肘，手过高"桶"形' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划水', '蛙泳', '高肘', '桶形'],
  },
  {
    id: 'drill-balance-015',
    name: 'Tennis Ball Breaststroke',
    nameZh: '网球蛙泳',
    category: 'balance',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['身体位置'],
    steps: ['夹网球练习身体线', '保持身体水平线', '不抬腿'],
    keyPoints: ['身体水平线', '夹球稳定', '不抬腿'],
    commonErrors: [{ error: '抬腿', correction: '保持腿部水平，不抬起' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['蛙泳', '身体位置', '网球', '水平'],
  },
  {
    id: 'drill-stroke-016',
    name: 'Mermaid Drill with Breathing',
    nameZh: '美人鱼带呼吸',
    category: 'stroke',
    strokes: ['butterfly', 'breaststroke'],
    level: 'L2',
    purpose: ['节奏训练', '呼吸技术'],
    steps: ['上身保持直立', '下身海豚踢', '保持呼吸'],
    keyPoints: ['协调', '海豚踢', '保持呼吸'],
    commonErrors: [{ error: '不协调', correction: '练习上身稳定与下身海豚踢的协调' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['美人鱼', '海豚踢', '呼吸', '协调'],
  },
  {
    id: 'drill-kick-020',
    name: 'Duck Feet',
    nameZh: '鸭子脚',
    category: 'kick',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['站姿转动踝关节练灵活', '外八字旋转', '全范围转动'],
    keyPoints: ['外八字旋转', '脚踝灵活性', '全范围转动'],
    commonErrors: [{ error: '脚踝不转动', correction: '主动旋转脚踝，全范围转动' }],
    recommendedSets: '陆上练习15-20次，重复3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['打腿', '蛙泳', '脚踝', '灵活性'],
  },
  {
    id: 'drill-catch-010',
    name: 'Corners Drill',
    nameZh: '角落练习',
    category: 'catch',
    strokes: ['breaststroke'],
    level: 'L3',
    purpose: ['抓水/划水', '呼吸技术'],
    steps: ['划臂角点加速内划', '找呼吸袋', '注意时机'],
    keyPoints: ['时机', '角点加速', '呼吸袋'],
    commonErrors: [{ error: '时机不对', correction: '在角点加速时找呼吸袋' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['划水', '蛙泳', '角点', '呼吸'],
  },
  {
    id: 'drill-breathing-009',
    name: 'Heads Up Breaststroke',
    nameZh: '抬头蛙泳',
    category: 'breathing',
    strokes: ['breaststroke'],
    level: 'L3',
    purpose: ['呼吸技术', '抓水/划水'],
    steps: ['抬头划水', '练呼吸与划臂分离', '保持分离动作'],
    keyPoints: ['分离动作', '抬头划水', '呼吸独立'],
    commonErrors: [{ error: '同步', correction: '分离呼吸与划臂动作' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['呼吸', '蛙泳', '抬头', '分离'],
  },
  {
    id: 'drill-catch-011',
    name: 'Shoot to Streamline',
    nameZh: '穿透漂流线',
    category: 'catch',
    strokes: ['breaststroke'],
    level: 'L3',
    purpose: ['抓水/划水', '身体位置'],
    steps: ['加速穿透"阻力点"', '回漂流线', '保持加速'],
    keyPoints: ['加速', '穿透阻力点', '回漂流线'],
    commonErrors: [{ error: '无力', correction: '加速推水，穿透阻力点' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['划水', '蛙泳', '加速', '穿透'],
  },
  {
    id: 'drill-stroke-017',
    name: 'No Stars',
    nameZh: '无星星',
    category: 'stroke',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['节奏训练'],
    steps: ['严格划-蹬分离', '避免抵消', '保持分离'],
    keyPoints: ['分离', '划-蹬分离', '避免抵消'],
    commonErrors: [{ error: '同时做', correction: '严格分离划臂和蹬腿' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['节奏', '蛙泳', '分离', '协调'],
  },

  // ============================================================
  // 5. 蝶泳Drill
  // ============================================================

  {
    id: 'drill-kick-021',
    name: 'Superman Dolphin Kick',
    nameZh: '超人海豚踢',
    category: 'kick',
    strokes: ['butterfly'],
    level: 'L1',
    purpose: ['打腿技术'],
    steps: ['俯卧海豚踢', '从髋部发力', '全身波浪'],
    keyPoints: ['从髋部发力', '波浪传导', '全身协调'],
    commonErrors: [{ error: '从膝盖发力', correction: '从髋部和核心发力' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['单臂蝶泳'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['海豚踢', '蝶泳', '超人', '波浪'],
  },
  {
    id: 'drill-kick-022',
    name: 'Streamline Dolphin Kick',
    nameZh: '流线型海豚踢',
    category: 'kick',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['打腿技术', '身体位置'],
    steps: ['流线型姿势海豚踢', '从髋到脚波浪', '保持流线型'],
    keyPoints: ['从髋到脚波浪', '波浪连贯', '保持流线型'],
    commonErrors: [{ error: '波浪断', correction: '保持从头到脚的连贯波浪' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['海豚踢', '蝶泳', '流线型', '波浪'],
  },
  {
    id: 'drill-kick-023',
    name: 'Dolphin Kick Face Down',
    nameZh: '俯卧海豚踢',
    category: 'kick',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['俯卧做海豚踢', '身体波浪传导', '从髋部发力'],
    keyPoints: ['身体波浪传导', '连贯波浪', '从髋部发力'],
    commonErrors: [{ error: '断', correction: '保持波浪连贯传导' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['游进'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['海豚踢', '蝶泳', '俯卧', '波浪'],
  },
  {
    id: 'drill-stroke-018',
    name: 'Mermaid Drill with Breathing',
    nameZh: '美人鱼带呼吸',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['呼吸技术', '节奏训练'],
    steps: ['美人鱼式保持呼吸', '下巴贴近水面', '上身直立'],
    keyPoints: ['下巴贴近水面', '下身海豚踢', '保持呼吸'],
    commonErrors: [{ error: '抬头过高', correction: '保持下巴贴近水面' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['美人鱼', '蝶泳', '呼吸', '海豚踢'],
  },
  {
    id: 'drill-stroke-019',
    name: 'Butterfly Body Wave',
    nameZh: '蝶泳身体波浪',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['节奏训练', '身体位置'],
    steps: ['头-胸-髋-脚波浪传导', '波浪连贯', '全身协调'],
    keyPoints: ['波浪连贯', '头-胸-髋-脚传导', '不停顿'],
    commonErrors: [{ error: '断裂', correction: '保持波浪从头到脚连贯传导' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['波浪', '蝶泳', '传导', '协调'],
  },
  {
    id: 'drill-stroke-020',
    name: 'One-Arm Butterfly',
    nameZh: '单臂蝶泳',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['单臂蝶泳', '保持节奏', '身体稳定'],
    keyPoints: ['保持节奏', '单臂划水', '身体稳定'],
    commonErrors: [{ error: '动作脱节', correction: '保持动作连贯流畅' }],
    recommendedSets: '每臂25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '蝶泳', '节奏', '划水'],
  },
  {
    id: 'drill-stroke-021',
    name: 'One-Arm and Breath',
    nameZh: '单臂带呼吸',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['呼吸技术', '抓水/划水'],
    steps: ['单臂蝶泳加呼吸', '注意呼吸时机', '保持节奏'],
    keyPoints: ['呼吸时机', '单臂划水', '节奏稳定'],
    commonErrors: [{ error: '时机不准', correction: '在划水推水阶段呼吸' }],
    recommendedSets: '每臂25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['连续'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['单臂', '蝶泳', '呼吸', '时机'],
  },
  {
    id: 'drill-catch-012',
    name: 'Standing Butterfly Arm Action',
    nameZh: '站立蝶泳划臂',
    category: 'catch',
    strokes: ['butterfly'],
    level: 'L1',
    purpose: ['抓水/划水'],
    steps: ['站立练习划臂', '高肘恢复', '控制路径'],
    keyPoints: ['高肘恢复', '划臂路径', '身体稳定'],
    commonErrors: [{ error: '肘过低', correction: '保持高肘恢复' }],
    recommendedSets: '陆上练习15-20次，重复3-5组',
    recommendedZones: ['Z1'],
    progressions: ['水中'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['划臂', '蝶泳', '站立', '高肘'],
  },
  {
    id: 'drill-stroke-022',
    name: 'Power Fly',
    nameZh: '强力蝶泳',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L4',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['全力蝶泳', '发挥力量', '保持节奏'],
    keyPoints: ['力量', '全力', '节奏稳定'],
    commonErrors: [{ error: '无力', correction: '全力划水，发挥最大力量' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z2-Z3'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['力量', '蝶泳', '全力', '强度'],
  },
  {
    id: 'drill-stroke-023',
    name: '2 + 2 + 2',
    nameZh: '两臂两腿交替',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L3',
    purpose: ['节奏训练', '抓水/划水'],
    steps: ['两臂两腿交替配合', '注意节奏', '保持协调'],
    keyPoints: ['节奏', '两臂两腿', '协调配合'],
    commonErrors: [{ error: '不协调', correction: '保持手臂和腿部的配合节奏' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['节奏', '蝶泳', '交替', '协调'],
  },
  {
    id: 'drill-stroke-024',
    name: 'Controlled Butterfly',
    nameZh: '控制蝶泳',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['节奏训练'],
    steps: ['控制蝶泳节奏', '节奏稳定', '不匆忙'],
    keyPoints: ['节奏稳定', '控制节奏', '不匆忙'],
    commonErrors: [{ error: '过快', correction: '放慢节奏，控制每个动作' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['节奏', '蝶泳', '控制', '稳定'],
  },
  {
    id: 'drill-catch-013',
    name: 'Grab and Go',
    nameZh: '无限流蝶泳',
    category: 'catch',
    strokes: ['butterfly'],
    level: 'L3',
    purpose: ['抓水/划水'],
    steps: ['抱推之间不停顿', '连续动作', '保持流畅'],
    keyPoints: ['连续', '不停顿', '流畅'],
    commonErrors: [{ error: '停顿', correction: '保持抱水和推水之间连续不停顿' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['划水', '蝶泳', '连续', '流畅'],
  },
  {
    id: 'drill-recovery-013',
    name: 'Pinkies Up',
    nameZh: '小指向上',
    category: 'recovery',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['移臂技术'],
    steps: ['恢复时小指向上', '避免拖肘', '肘高过头顶'],
    keyPoints: ['小指向上', '肘高过头顶', '避免拖肘'],
    commonErrors: [{ error: '拖肘', correction: '保持小指向上，肘高过头顶' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['移臂', '蝶泳', '小指', '高肘'],
  },
  {
    id: 'drill-balance-016',
    name: 'Short/Long Balance',
    nameZh: '短长平衡',
    category: 'balance',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['身体位置', '核心稳定性'],
    steps: ['身体位置平衡', '保持稳定', '不下沉'],
    keyPoints: ['平衡', '身体稳定', '不下沉'],
    commonErrors: [{ error: '下沉', correction: '收紧核心，保持身体位置' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['平衡', '蝶泳', '身体位置', '核心'],
  },
  {
    id: 'drill-stroke-025',
    name: 'Bowing',
    nameZh: '鞠躬',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['节奏训练', '核心稳定性'],
    steps: ['腹部收紧下压', '回弹', '核心控制'],
    keyPoints: ['核心控制', '腹部收紧下压', '回弹'],
    commonErrors: [{ error: '松散', correction: '收紧腹部，控制下压和回弹' }],
    recommendedSets: '陆上或水中练习15-20次，重复3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['核心', '蝶泳', '下压', '回弹'],
  },
  {
    id: 'drill-balance-017',
    name: 'Chest Balance',
    nameZh: '低胸平衡点',
    category: 'balance',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['身体位置'],
    steps: ['低胸平衡点', '骑"下坡"的感觉', '保持低胸位'],
    keyPoints: ['低胸位', '下坡感', '平衡稳定'],
    commonErrors: [{ error: '高位', correction: '保持胸部低位置，下压' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: '100 More Drills',
    tags: ['平衡', '蝶泳', '低胸', '下坡'],
  },
  {
    id: 'drill-stroke-026',
    name: 'Body Wave',
    nameZh: '身体波浪',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['节奏训练'],
    steps: ['波浪从头传到脚', '连贯传导', '全身协调'],
    keyPoints: ['连贯', '从头传到脚', '波浪传导'],
    commonErrors: [{ error: '从脚开始', correction: '从头开始波浪传导' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swimming Tech',
    tags: ['波浪', '蝶泳', '传导', '连贯'],
  },
  {
    id: 'drill-stroke-027',
    name: 'Butterfly One-Arm',
    nameZh: '单臂蝶泳',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['抓水/划水', '节奏训练'],
    steps: ['单臂蝶泳', '保持节奏', '身体稳定'],
    keyPoints: ['节奏', '单臂稳定', '身体稳定'],
    commonErrors: [{ error: '不稳', correction: '收紧核心，保持身体稳定' }],
    recommendedSets: '每臂25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: ['加呼吸'],
    contraindications: [],
    source: 'Swimming Tech',
    tags: ['单臂', '蝶泳', '稳定', '节奏'],
  },
  {
    id: 'drill-stroke-028',
    name: 'Butterfly to Butterfly',
    nameZh: '超人到蝶泳',
    category: 'stroke',
    strokes: ['butterfly'],
    level: 'L3',
    purpose: ['节奏训练', '打腿技术'],
    steps: ['Superman Dolphin → Butterfly', '从海豚踢过渡到蝶泳', '保持流畅'],
    keyPoints: ['过渡', '流畅', '海豚踢到蝶泳'],
    commonErrors: [{ error: '断', correction: '保持从海豚踢到蝶泳的流畅过渡' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['过渡', '蝶泳', '海豚踢', '流畅'],
  },

  // ============================================================
  // 6. 转身Drill（各泳姿）
  // ============================================================

  // --- 6.1 自由泳/仰泳翻转转身 ---
  
  {
    id: 'drill-start-001',
    name: 'Streamline Jumps',
    nameZh: '流线型跳跃',
    category: 'start',
    strokes: ['all'],
    level: 'L1',
    purpose: ['出发技术'],
    steps: ['流线型姿势跳入水中', '头顶指向池底', '保持流线型'],
    keyPoints: ['头顶指向池底', '保持流线型', '身体稳定'],
    commonErrors: [{ error: '身体弯曲', correction: '收紧核心，保持身体成一直线' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: ['入水后海豚踢'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '流线型', '跳跃', '入水'],
  },
  {
    id: 'drill-turn-001',
    name: 'Jump and Somersault',
    nameZh: '跳跃翻转',
    category: 'turn',
    strokes: ['freestyle', 'backstroke'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['跳向墙壁后做翻转', '注意翻转时机', '紧凑翻转'],
    keyPoints: ['翻转时机', '紧凑翻转', '团身'],
    commonErrors: [{ error: '到墙过远', correction: '调整跳跃距离，靠近墙壁' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '翻转', '跳跃', '时机'],
  },
  {
    id: 'drill-turn-002',
    name: 'Push-off and Somersault',
    nameZh: '蹬壁翻转',
    category: 'turn',
    strokes: ['freestyle', 'backstroke'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['蹬壁后翻转', '注意时机', '紧凑翻转'],
    keyPoints: ['时机', '紧凑翻转', '蹬壁'],
    commonErrors: [{ error: '时机不准', correction: '调整蹬壁和翻转的时机' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '翻转', '蹬壁', '时机'],
  },
  {
    id: 'drill-turn-003',
    name: 'One-Arm Extension and Flip',
    nameZh: '单臂伸展翻转',
    category: 'turn',
    strokes: ['freestyle', 'backstroke'],
    level: 'L3',
    purpose: ['转身技术'],
    steps: ['单臂入水后翻转', '注意入水手臂', '保持流线型'],
    keyPoints: ['入水手臂', '单臂伸展', '翻转'],
    commonErrors: [{ error: '时机不准', correction: '调整单臂入水与翻转的配合' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '翻转', '单臂', '伸展'],
  },
  {
    id: 'drill-turn-004',
    name: 'Freestyle Turn',
    nameZh: '自由泳转身',
    category: 'turn',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['接近墙壁→翻滚→蹬壁', '翻转时机', '保持流线型'],
    keyPoints: ['翻转时机', '紧凑翻转', '流线型蹬壁'],
    commonErrors: [{ error: '用旗帜练习', correction: '利用仰泳旗帜判断时机' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '自由泳', '翻转', '蹬壁'],
  },
  {
    id: 'drill-turn-005',
    name: 'Freestyle Turn with Flag',
    nameZh: '带旗自由泳转身',
    category: 'turn',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['利用仰泳旗帜判断时机', '看底部黑线', '不抬头'],
    keyPoints: ['看底部黑线', '利用旗帜判断', '不抬头'],
    commonErrors: [{ error: '抬头', correction: '保持头部位置，不抬头' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '自由泳', '旗帜', '时机'],
  },
  {
    id: 'drill-turn-006',
    name: 'Freestyle Turn with Kickboard',
    nameZh: '带板自由泳转身',
    category: 'turn',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['夹踢腿板转身', '保持流线', '紧凑翻转'],
    keyPoints: ['保持流线', '紧凑翻转', '夹板稳定'],
    commonErrors: [{ error: '失去流线', correction: '保持身体流线型' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '自由泳', '夹板', '流线型'],
  },
  {
    id: 'drill-turn-007',
    name: 'Backstroke Turn',
    nameZh: '仰泳翻转转身',
    category: 'turn',
    strokes: ['backstroke'],
    level: 'L3',
    purpose: ['转身技术'],
    steps: ['仰泳标志处翻转', '时机判断', '保持流线型'],
    keyPoints: ['时机判断', '翻转紧凑', '流线型蹬壁'],
    commonErrors: [{ error: '用旗', correction: '利用旗帜判断翻转时机' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '仰泳', '翻转', '旗帜'],
  },
  {
    id: 'drill-stroke-029',
    name: 'Corkscrew Swimming',
    nameZh: '螺旋游泳',
    category: 'stroke',
    strokes: ['freestyle', 'backstroke'],
    level: 'L3',
    purpose: ['转身技术', '节奏训练'],
    steps: ['游进中做旋转', '旋转时机', '保持节奏'],
    keyPoints: ['旋转时机', '保持节奏', '全身协调'],
    commonErrors: [{ error: '过早', correction: '控制旋转时机，不过早' }],
    recommendedSets: '25-50米，重复2-3次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['旋转', '转身', '螺旋', '协调'],
  },
  {
    id: 'drill-kick-024',
    name: 'Streamline Dolphin Kick',
    nameZh: '流线型海豚踢',
    category: 'kick',
    strokes: ['freestyle', 'backstroke', 'butterfly'],
    level: 'L2',
    purpose: ['打腿技术', '转身技术'],
    steps: ['水下海豚踢', '从髋部发力', '15米距离'],
    keyPoints: ['从髋部发力', '波浪传导', '出发转身后的关键推进段'],
    commonErrors: [{ error: '膝盖弯曲', correction: '保持腿部伸直，从髋部驱动' }],
    recommendedSets: '15米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: ['15米距离'],
    contraindications: [],
    source: 'Swimming Tech',
    tags: ['海豚踢', '流线型', '出发', '转身'],
  },
  {
    id: 'drill-turn-008',
    name: 'Flip Turn',
    nameZh: '翻转转身',
    category: 'turn',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['收紧团身→下巴收紧→近墙翻转→脚触壁即推', '紧凑翻转', '快速蹬壁'],
    keyPoints: ['紧凑翻转', '团身', '快速蹬壁'],
    commonErrors: [{ error: '拖延', correction: '收紧团身，快速翻转' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swim Smooth',
    tags: ['转身', '翻转', '紧凑', '蹬壁'],
  },
  {
    id: 'drill-kick-025',
    name: 'Head to Toe Dolphin',
    nameZh: '从头到脚海豚踢',
    category: 'kick',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['打腿技术'],
    steps: ['头先下→胸部→髋部→腿部依次传导', '连贯波浪', '全身协调'],
    keyPoints: ['连贯波浪', '依次传导', '从头到脚'],
    commonErrors: [{ error: '断开', correction: '保持波浪连贯传导' }],
    recommendedSets: '15-25米，重复3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'Swimming Tech',
    tags: ['海豚踢', '波浪', '传导', '连贯'],
  },

  // --- 6.2 蝶泳/蛙泳转身 ---
  
  {
    id: 'drill-turn-009',
    name: 'Basic Two-Hand Open Turn',
    nameZh: '基础双手开放转身',
    category: 'turn',
    strokes: ['butterfly', 'breaststroke'],
    level: 'L1',
    purpose: ['转身技术'],
    steps: ['双手触壁转身', '保持紧凑', '快速转身'],
    keyPoints: ['紧凑', '双手触壁', '快速转身'],
    commonErrors: [{ error: '松散', correction: '收紧身体，快速转身' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '开放转身', '双手', '紧凑'],
  },
  {
    id: 'drill-turn-010',
    name: 'Two-Hand Open Turn with Backstroke Push-off',
    nameZh: '双手开放转身带仰泳蹬壁',
    category: 'turn',
    strokes: ['butterfly', 'breaststroke'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['开放转身接仰泳', '转身后仰泳蹬壁', '保持衔接'],
    keyPoints: ['衔接', '转身后仰泳蹬壁', '流畅'],
    commonErrors: [{ error: '断开', correction: '保持转身与蹬壁的流畅衔接' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '开放转身', '仰泳', '衔接'],
  },
  {
    id: 'drill-turn-011',
    name: 'Breaststroke Pullout',
    nameZh: '蛙泳划水过渡',
    category: 'turn',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['划水结束后收腿蹬腿', '注意时机', '不过早/晚'],
    keyPoints: ['时机', '划水到蹬腿', '节奏'],
    commonErrors: [{ error: '过早/晚', correction: '调整收腿蹬腿的时机' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '蛙泳', 'Pullout', '时机'],
  },
  {
    id: 'drill-turn-012',
    name: 'Breaststroke Turn',
    nameZh: '蛙泳转身',
    category: 'turn',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['转身触壁', '注意时机', '快速转身'],
    keyPoints: ['时机', '快速转身', '紧凑'],
    commonErrors: [{ error: '太慢', correction: '加快转身速度，保持紧凑' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '蛙泳', '触壁', '快速'],
  },
  {
    id: 'drill-turn-013',
    name: 'Butterfly Finish',
    nameZh: '蝶泳触边',
    category: 'turn',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['双手触边', '注意时机', '动作连贯'],
    keyPoints: ['时机', '双手触边', '动作连贯'],
    commonErrors: [{ error: '动作脱节', correction: '保持动作连贯流畅' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['触边', '蝶泳', '双手', '时机'],
  },
  {
    id: 'drill-turn-014',
    name: 'Butterfly Breakout Drill',
    nameZh: '蝶泳出发突破',
    category: 'turn',
    strokes: ['butterfly'],
    level: 'L3',
    purpose: ['转身技术', '出发技术'],
    steps: ['水下海豚踢后破水面', '破水时机', '保持流线型'],
    keyPoints: ['破水时机', '水下海豚踢', '流线型'],
    commonErrors: [{ error: '多加练习', correction: '练习破水时机' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '蝶泳', '破水', '海豚踢'],
  },
  {
    id: 'drill-turn-015',
    name: 'Butterfly Turn',
    nameZh: '蝶泳转身',
    category: 'turn',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['转身技术'],
    steps: ['开放转身', '保持紧凑', '快速转身'],
    keyPoints: ['紧凑', '开放转身', '快速'],
    commonErrors: [{ error: '松散', correction: '收紧身体，快速转身' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '蝶泳', '开放转身', '紧凑'],
  },
  {
    id: 'drill-turn-016',
    name: 'Fly to Back Turn',
    nameZh: '蝶泳到仰泳转身',
    category: 'turn',
    strokes: ['butterfly', 'backstroke'],
    level: 'L3',
    purpose: ['转身技术'],
    steps: ['蝶泳→仰泳转换', '旋转', '保持连贯'],
    keyPoints: ['旋转', '连贯', '转换流畅'],
    commonErrors: [{ error: '不连贯', correction: '保持转换流畅' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '蝶泳', '仰泳', '转换'],
  },
  {
    id: 'drill-turn-017',
    name: 'Backstroke to Breaststroke Turn',
    nameZh: '仰泳到蛙泳转身',
    category: 'turn',
    strokes: ['backstroke', 'breaststroke'],
    level: 'L3',
    purpose: ['转身技术'],
    steps: ['仰泳→蛙泳转换', '旋转', '动作连贯'],
    keyPoints: ['旋转', '动作连贯', '转换流畅'],
    commonErrors: [{ error: '动作断', correction: '保持转换流畅连贯' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '仰泳', '蛙泳', '转换'],
  },
  {
    id: 'drill-turn-018',
    name: 'Advanced Backstroke to Breaststroke Turn (Back Flip)',
    nameZh: '高级仰蛙转身(背翻)',
    category: 'turn',
    strokes: ['backstroke', 'breaststroke'],
    level: 'L4',
    purpose: ['转身技术'],
    steps: ['背面翻转', '保持紧凑', '快速转换'],
    keyPoints: ['紧凑', '背面翻转', '快速'],
    commonErrors: [{ error: '失去方向', correction: '保持身体稳定，控制方向' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '仰泳', '蛙泳', '背翻'],
  },
  {
    id: 'drill-turn-019',
    name: 'Advanced Backstroke to Breaststroke Turn (Crossover)',
    nameZh: '高级仰蛙转身(交叉)',
    category: 'turn',
    strokes: ['backstroke', 'breaststroke'],
    level: 'L4',
    purpose: ['转身技术'],
    steps: ['交叉脚步', '保持流畅', '快速转换'],
    keyPoints: ['流畅', '交叉脚步', '快速'],
    commonErrors: [{ error: '不流畅', correction: '练习交叉脚步，保持流畅' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '仰泳', '蛙泳', '交叉'],
  },
  {
    id: 'drill-turn-020',
    name: 'Breaststroke to Freestyle Turn',
    nameZh: '蛙泳到自由泳转身',
    category: 'turn',
    strokes: ['breaststroke', 'freestyle'],
    level: 'L3',
    purpose: ['转身技术'],
    steps: ['蛙泳→自由泳转换', '保持衔接', '流畅转换'],
    keyPoints: ['衔接', '流畅', '转换'],
    commonErrors: [{ error: '不流畅', correction: '保持转换流畅衔接' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['转身', '蛙泳', '自由泳', '转换'],
  },

  // ============================================================
  // 7. 出发Drill（各泳姿）
  // ============================================================

  {
    id: 'drill-start-002',
    name: 'Jumping from the Blocks',
    nameZh: '跳台跳跃',
    category: 'start',
    strokes: ['all'],
    level: 'L1',
    purpose: ['出发技术'],
    steps: ['从跳台跳入水中', '团身', '保持稳定'],
    keyPoints: ['团身', '身体稳定', '入水角度'],
    commonErrors: [{ error: '身体直', correction: '团身入水，保持稳定' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '跳台', '跳跃', '团身'],
  },
  {
    id: 'drill-start-003',
    name: 'Standing Streamline Jump',
    nameZh: '站立流线型跳跃',
    category: 'start',
    strokes: ['all'],
    level: 'L1',
    purpose: ['出发技术'],
    steps: ['站立跳入水中成流线型', '头顶指向池底', '保持流线型'],
    keyPoints: ['头顶指向池底', '成流线型', '身体稳定'],
    commonErrors: [{ error: '弯曲', correction: '收紧核心，保持身体成一直线' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '流线型', '跳跃', '入水'],
  },
  {
    id: 'drill-start-004',
    name: 'Streamline Jump from the Blocks',
    nameZh: '跳台流线型跳跃',
    category: 'start',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['跳台流线型入水', '成流线型', '保持紧凑'],
    keyPoints: ['成流线型', '紧凑', '入水角度'],
    commonErrors: [{ error: '松散', correction: '收紧身体，保持流线型' }],
    recommendedSets: '5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '跳台', '流线型', '入水'],
  },
  {
    id: 'drill-start-005',
    name: 'Relay Starts',
    nameZh: '接力出发',
    category: 'start',
    strokes: ['all'],
    level: 'L3',
    purpose: ['出发技术'],
    steps: ['准备→出发→入水', '反应时间', '快速出发'],
    keyPoints: ['反应时间', '快速出发', '时机'],
    commonErrors: [{ error: '迟钝', correction: '提高反应速度，快速出发' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: ['简单/高级'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '接力', '反应', '时机'],
  },
  {
    id: 'drill-start-006',
    name: 'Simple Relay Start',
    nameZh: '简单接力出发',
    category: 'start',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['简化流程', '快速出发', '保持稳定'],
    keyPoints: ['快速', '简化流程', '稳定'],
    commonErrors: [{ error: '复杂', correction: '简化流程，快速出发' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '接力', '简单', '快速'],
  },
  {
    id: 'drill-start-007',
    name: 'Advanced Relay Start',
    nameZh: '高级接力出发',
    category: 'start',
    strokes: ['all'],
    level: 'L4',
    purpose: ['出发技术'],
    steps: ['复杂流程', '协调', '快速出发'],
    keyPoints: ['协调', '复杂流程', '快速'],
    commonErrors: [{ error: '不协调', correction: '练习复杂流程的协调配合' }],
    recommendedSets: '练习8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '接力', '高级', '协调'],
  },
  {
    id: 'drill-start-008',
    name: 'Setup on the Blocks',
    nameZh: '跳台设置',
    category: 'start',
    strokes: ['all'],
    level: 'L1',
    purpose: ['出发技术'],
    steps: ['正确跳台站位', '保持稳定', '准备出发'],
    keyPoints: ['稳定', '正确站位', '准备姿势'],
    commonErrors: [{ error: '不稳', correction: '调整站位，保持稳定' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '跳台', '站位', '准备'],
  },
  {
    id: 'drill-start-009',
    name: 'Dive from the Blocks',
    nameZh: '跳台跳水',
    category: 'start',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['从跳台潜入水中', '入水角度', '保持流线型'],
    keyPoints: ['入水角度', '流线型', '入水姿势'],
    commonErrors: [{ error: '角度不佳', correction: '调整入水角度，保持流线型' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: ['拿 noodle'],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '跳台', '跳水', '入水'],
  },
  {
    id: 'drill-start-010',
    name: 'Dive from the Blocks Plus Noodle',
    nameZh: '跳台拿棒跳水',
    category: 'start',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['持海龟棒入水', '保持流线', '棒不掉落'],
    keyPoints: ['保持流线', '持棒稳定', '入水姿势'],
    commonErrors: [{ error: '棒掉落', correction: '抓紧棒，保持流线型' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '跳台', '持棒', '流线型'],
  },
  {
    id: 'drill-start-011',
    name: 'Streamline Diving',
    nameZh: '流线型跳水',
    category: 'start',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['入水后保持流线型', '紧凑', '保持稳定'],
    keyPoints: ['紧凑', '流线型', '入水姿势'],
    commonErrors: [{ error: '散', correction: '收紧身体，保持流线型' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '跳水', '流线型', '紧凑'],
  },
  {
    id: 'drill-start-012',
    name: 'Butterfly Start',
    nameZh: '蝶泳出发',
    category: 'start',
    strokes: ['butterfly'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['蝶泳入水姿势', '入水角度', '保持流线型'],
    keyPoints: ['入水角度', '流线型', '蝶泳姿势'],
    commonErrors: [{ error: '不适', correction: '调整入水角度和姿势' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '蝶泳', '入水', '姿势'],
  },
  {
    id: 'drill-start-013',
    name: 'Breaststroke Start',
    nameZh: '蛙泳出发',
    category: 'start',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['蛙泳入水姿势', '注意时机', '保持流线型'],
    keyPoints: ['时机', '流线型', '蛙泳姿势'],
    commonErrors: [{ error: '过早', correction: '调整入水时机' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '蛙泳', '入水', '时机'],
  },
  {
    id: 'drill-start-014',
    name: 'Freestyle Start',
    nameZh: '自由泳出发',
    category: 'start',
    strokes: ['freestyle'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['标准自由泳入水', '入水角度', '保持流线型'],
    keyPoints: ['入水', '流线型', '标准姿势'],
    commonErrors: [{ error: '角度不佳', correction: '调整入水角度' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '自由泳', '入水', '标准'],
  },
  {
    id: 'drill-start-015',
    name: 'Backstroke Start Setup, Launch, Entry',
    nameZh: '仰泳出发设置/启动/入水',
    category: 'start',
    strokes: ['backstroke'],
    level: 'L3',
    purpose: ['出发技术'],
    steps: ['设置→启动→入水', '时机', '保持流线型'],
    keyPoints: ['时机', '设置→启动→入水', '流线型'],
    commonErrors: [{ error: '过早/晚', correction: '调整出发时机' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '仰泳', '设置', '启动'],
  },
  {
    id: 'drill-start-016',
    name: 'Backstroke Start',
    nameZh: '仰泳出发',
    category: 'start',
    strokes: ['backstroke'],
    level: 'L2',
    purpose: ['出发技术'],
    steps: ['背对水面出发', '反应', '保持流线型'],
    keyPoints: ['反应', '背对水面', '流线型'],
    commonErrors: [{ error: '迟', correction: '提高反应速度' }],
    recommendedSets: '练习5-8次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '仰泳', '背对', '反应'],
  },

  // ============================================================
  // 8. 体能训练Drill（陆上）
  // ============================================================

  // --- 8.1 核心力量训练 ---
  
  {
    id: 'drill-dryland-001',
    name: 'Plank Hold',
    nameZh: '平板支撑',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['俯卧姿势', '前臂和脚尖支撑', '保持身体成一直线', '1分钟+保持'],
    keyPoints: ['核心收紧', '身体成一直线', '不塌腰'],
    commonErrors: [{ error: '塌腰', correction: '收紧腹部，保持身体成一直线' }],
    recommendedSets: '1分钟一组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['核心', '平板', '陆上', '稳定性'],
  },
  {
    id: 'drill-dryland-002',
    name: 'Back Plank (仰撑)',
    nameZh: '仰撑',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['仰卧姿势', '手掌和脚跟支撑', '保持身体成一直线', '45秒-1分钟'],
    keyPoints: ['臀部抬起', '核心收紧', '身体成一直线'],
    commonErrors: [{ error: '臀部塌陷', correction: '收紧臀部和核心，保持臀部抬起' }],
    recommendedSets: '45秒-1分钟一组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['核心', '仰撑', '陆上', '稳定性'],
  },
  {
    id: 'drill-dryland-003',
    name: 'Russian Twist',
    nameZh: '俄罗斯转体',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性', '身体滚动'],
    steps: ['坐姿', '膝盖弯曲', '上身向后倾斜', '药球转动'],
    keyPoints: ['腹内外斜肌', '旋转力量', '控制节奏'],
    commonErrors: [{ error: '动作过快', correction: '放慢速度，控制转动幅度' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['核心', '转体', '陆上', '旋转'],
  },
  {
    id: 'drill-dryland-004',
    name: 'V-ups',
    nameZh: 'V字卷腹',
    category: 'dryland',
    strokes: ['all'],
    level: 'L3',
    purpose: ['核心稳定性'],
    steps: ['仰卧', '手臂和腿同时抬起', '身体成V形', '控制回落'],
    keyPoints: ['整体收缩', '手臂和腿同时抬起', '控制节奏'],
    commonErrors: [{ error: '动作不完整', correction: '完全抬起，身体成V形' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['核心', 'V字', '陆上', '腹肌'],
  },
  {
    id: 'drill-dryland-005',
    name: 'Log Roll',
    nameZh: '圆木滚动',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性', '身体滚动'],
    steps: ['仰卧', '核心驱动旋转', '绕轴旋转', '保持身体成一直线'],
    keyPoints: ['核心驱动旋转', '绕轴旋转', '身体稳定'],
    commonErrors: [{ error: '仅用手臂', correction: '从核心发力，带动身体旋转' }],
    recommendedSets: '每侧10-15次，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['核心', '滚动', '陆上', '旋转'],
  },
  {
    id: 'drill-dryland-006',
    name: 'Crunch',
    nameZh: '卷腹',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['仰卧', '膝盖弯曲', '上身抬起', '肩胛骨离地'],
    keyPoints: ['经典卷腹', '腹肌收缩', '颈部放松'],
    commonErrors: [{ error: '颈部用力', correction: '放松颈部，用腹肌发力' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['颈椎伤'],
    source: 'DrillBook 2E',
    tags: ['核心', '卷腹', '陆上', '腹肌'],
  },
  {
    id: 'drill-dryland-007',
    name: 'Superman Extension',
    nameZh: '超人伸展',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['俯卧', '手臂和腿同时抬起', '保持2-3秒', '缓慢回落'],
    keyPoints: ['下背', '背伸', '手臂和腿同时抬起'],
    commonErrors: [{ error: '仅抬起上半身', correction: '手臂和腿同时抬起' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['核心', '超人', '陆上', '背伸'],
  },

  // --- 8.2 上肢力量训练 ---
  
  {
    id: 'drill-dryland-008',
    name: 'Push-ups',
    nameZh: '俯卧撑',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['俯卧', '手掌支撑', '身体成一直线', '胸部触地后推起'],
    keyPoints: ['胸、 triceps', '推力', '标准俯卧撑'],
    commonErrors: [{ error: '腰部塌陷', correction: '收紧核心，保持身体成一直线' }],
    recommendedSets: '10-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤', '腰伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '俯卧撑', '陆上', '推力'],
  },
  {
    id: 'drill-dryland-009',
    name: 'Diamond Push-ups',
    nameZh: '钻石俯卧撑',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['俯卧', '双手拇指和食指成钻石形', '窄距俯卧撑', '胸部触地后推起'],
    keyPoints: ['triceps', '三头肌', '窄距俯卧撑'],
    commonErrors: [{ error: '手距过宽', correction: '保持双手成钻石形，窄距' }],
    recommendedSets: '8-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤', '腰伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '三头肌', '陆上', '窄距'],
  },
  {
    id: 'drill-dryland-010',
    name: 'Upright Row',
    nameZh: '直立划船',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['直立', '双手持哑铃', '肘部抬高划船', '控制节奏'],
    keyPoints: ['肩、上背', '上拉', '直立划船'],
    commonErrors: [{ error: '重量过大', correction: '选择适当重量，控制动作' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '划船', '陆上', '肩背'],
  },
  {
    id: 'drill-dryland-011',
    name: 'Seated Row',
    nameZh: '坐姿划船',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['坐姿', '双手握把手', '向后拉', '肩胛骨夹紧'],
    keyPoints: ['背部', '拉力', '坐姿划船'],
    commonErrors: [{ error: '弓背', correction: '保持背部挺直，肩胛骨夹紧' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '划船', '陆上', '背部'],
  },
  {
    id: 'drill-dryland-012',
    name: 'Bent-Over Row',
    nameZh: '屈体划船',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['屈体', '背部挺直', '双手持哑铃', '向上拉'],
    keyPoints: ['背阔肌', '下拉', '屈体划船'],
    commonErrors: [{ error: '腰部代偿', correction: '保持背部挺直，用背阔肌发力' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '划船', '陆上', '背阔肌'],
  },
  {
    id: 'drill-dryland-013',
    name: 'Straight-Arm Row',
    nameZh: '直臂划船',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['屈体', '直臂', '向后拉', '背阔肌发力'],
    keyPoints: ['背阔肌', '隔离背阔', '直臂划船'],
    commonErrors: [{ error: '借力', correction: '保持直臂，用背阔肌发力' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['上肢', '划船', '陆上', '背阔肌'],
  },
  {
    id: 'drill-dryland-014',
    name: 'Triceps Extension',
    nameZh: '三头肌伸展',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['站立或坐姿', '双手持哑铃过头', '弯曲肘部', '伸展'],
    keyPoints: ['triceps', '伸展', '肱三头肌'],
    commonErrors: [{ error: '肘外展', correction: '保持肘部贴近头部' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '三头肌', '陆上', '伸展'],
  },
  {
    id: 'drill-dryland-015',
    name: 'Bent-Over Lateral Raise',
    nameZh: '屈体侧平举',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['屈体', '双手持哑铃', '侧平举', '控制节奏'],
    keyPoints: ['三角肌', '外展', '侧平举'],
    commonErrors: [{ error: '重量过大', correction: '选择适当重量，控制动作' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '三角肌', '陆上', '外展'],
  },
  {
    id: 'drill-dryland-016',
    name: 'Shoulder Blade Pinch',
    nameZh: '肩胛骨夹紧',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['站立或坐姿', '肩胛骨向后夹紧', '保持2-3秒', '放松'],
    keyPoints: ['肩胛', '稳定', '挤压肩胛'],
    commonErrors: [{ error: '仅用手', correction: '用肩胛骨发力夹紧' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['上肢', '肩胛', '陆上', '稳定'],
  },
  {
    id: 'drill-dryland-017',
    name: 'Shoulder Retraction with External Rotation',
    nameZh: '肩外旋回收',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['站立', '肘部弯曲90°', '外旋', '肩胛骨回收'],
    keyPoints: ['肩袖', '稳定', '外旋回收'],
    commonErrors: [{ error: '旋转不足', correction: '充分外旋，肩胛骨回收' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '肩袖', '陆上', '外旋'],
  },
  {
    id: 'drill-dryland-018',
    name: 'Standing Internal Rotation',
    nameZh: '站姿内旋',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['站立', '肘部贴身', '内旋', '控制节奏'],
    keyPoints: ['肩袖', '内旋', '内旋训练'],
    commonErrors: [{ error: '阻力过大', correction: '选择适当阻力，控制动作' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '肩袖', '陆上', '内旋'],
  },
  {
    id: 'drill-dryland-019',
    name: 'Standing External Rotation',
    nameZh: '站姿外旋',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['站立', '肘部贴身', '外旋', '控制节奏'],
    keyPoints: ['肩袖', '外旋', '外旋训练'],
    commonErrors: [{ error: '肩部耸高', correction: '保持肩部放松，不耸肩' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '肩袖', '陆上', '外旋'],
  },
  {
    id: 'drill-dryland-020',
    name: 'Full Can',
    nameZh: '全幅Can练习',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['站立', '手臂向前上方抬起', '拇指向上', '全幅度'],
    keyPoints: ['冈上肌', '肩部稳定', '全幅度can练习'],
    commonErrors: [{ error: '动作受限', correction: '保持全幅度，控制动作' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['上肢', '冈上肌', '陆上', '稳定'],
  },

  // --- 8.3 下肢力量训练 ---
  
  {
    id: 'drill-dryland-021',
    name: 'Squats',
    nameZh: '深蹲',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['核心稳定性'],
    steps: ['站立', '双脚与肩同宽', '下蹲', '膝盖不超过脚尖'],
    keyPoints: ['臀大肌、股四头肌', '下肢力量', '深蹲'],
    commonErrors: [{ error: '膝盖超伸', correction: '保持膝盖不超过脚尖' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['膝盖伤'],
    source: 'DrillBook 2E',
    tags: ['下肢', '深蹲', '陆上', '腿部力量'],
  },
  {
    id: 'drill-dryland-022',
    name: 'Squat Hold',
    nameZh: '半蹲保持',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['半蹲姿势', '保持30-60秒', '核心收紧', '膝盖稳定'],
    keyPoints: ['下肢', '耐力', '半蹲保持'],
    commonErrors: [{ error: '姿势变形', correction: '保持姿势稳定，核心收紧' }],
    recommendedSets: '30-60秒一组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['膝盖伤'],
    source: 'DrillBook 2E',
    tags: ['下肢', '半蹲', '陆上', '耐力'],
  },
  {
    id: 'drill-dryland-023',
    name: 'Lunges',
    nameZh: '箭步蹲',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['核心稳定性'],
    steps: ['站立', '向前迈一大步', '下蹲', '前膝不超过脚尖'],
    keyPoints: ['髋部', '单腿力量', '箭步蹲'],
    commonErrors: [{ error: '前膝过伸', correction: '保持前膝不超过脚尖' }],
    recommendedSets: '每侧10-15次，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['膝盖伤'],
    source: 'DrillBook 2E',
    tags: ['下肢', '箭步蹲', '陆上', '单腿'],
  },
  {
    id: 'drill-dryland-024',
    name: 'Reaction Jumps',
    nameZh: '反应跳跃',
    category: 'dryland',
    strokes: ['all'],
    level: 'L3',
    purpose: ['核心稳定性'],
    steps: ['站立', '快速跳跃', '轻柔落地', '立即再次跳跃'],
    keyPoints: ['下肢', '爆发', '反应跳跃'],
    commonErrors: [{ error: '落地过重', correction: '轻柔落地，立即反应' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z2'],
    progressions: [],
    contraindications: ['膝盖伤', '踝关节伤'],
    source: 'DrillBook 2E',
    tags: ['下肢', '跳跃', '陆上', '爆发'],
  },

  // --- 8.4 柔韧性训练 ---
  
  {
    id: 'drill-dryland-025',
    name: 'Sitting Ankle Stretch',
    nameZh: '坐姿脚踝伸展',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['髋部灵活性', '核心稳定性'],
    steps: ['坐姿', '脚踝转动', '多方向', '全范围'],
    keyPoints: ['踝关节灵活性', '坐姿脚踝转动', '多方向转动'],
    commonErrors: [{ error: '太快', correction: '放慢速度，全范围转动' }],
    recommendedSets: '每侧10-15次，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['踝关节伤'],
    source: 'DrillBook 2E',
    tags: ['柔韧', '脚踝', '陆上', '灵活性'],
  },
  {
    id: 'drill-dryland-026',
    name: '站姿脚踝转动',
    nameZh: '站姿脚踝转动',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['髋部灵活性', '核心稳定性'],
    steps: ['站立', '单脚踝转动', '多方向', '全范围'],
    keyPoints: ['踝关节灵活性', '多方向转动', '不彻底'],
    commonErrors: [{ error: '不彻底', correction: '全范围转动，充分伸展' }],
    recommendedSets: '每侧10-15次，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['踝关节伤'],
    source: 'DrillBook 2E',
    tags: ['柔韧', '脚踝', '陆上', '灵活性'],
  },
  {
    id: 'drill-dryland-027',
    name: 'Duck Feet',
    nameZh: '鸭子脚',
    category: 'dryland',
    strokes: ['breaststroke'],
    level: 'L2',
    purpose: ['髋部灵活性', '核心稳定性'],
    steps: ['坐姿或站姿', '脚踝外八字旋转', '全范围', '缓慢转动'],
    keyPoints: ['脚踝旋转', '外八字旋转', '不到位'],
    commonErrors: [{ error: '不到位', correction: '全范围旋转，充分伸展' }],
    recommendedSets: '15-20次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['踝关节伤'],
    source: 'DrillBook 2E',
    tags: ['柔韧', '脚踝', '陆上', '外八字'],
  },
  {
    id: 'drill-dryland-028',
    name: '肩部拉伸',
    nameZh: '肩部拉伸',
    category: 'dryland',
    strokes: ['all'],
    level: 'L1',
    purpose: ['髋部灵活性', '核心稳定性'],
    steps: ['站立或坐姿', '手臂过头', '向后拉伸', '保持15-30秒'],
    keyPoints: ['肩关节活动度', '高肘恢复需要', '拉伸不足'],
    commonErrors: [{ error: '拉伸不足', correction: '充分拉伸，保持时间' }],
    recommendedSets: '每侧保持15-30秒，3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['肩伤'],
    source: 'DrillBook 2E',
    tags: ['柔韧', '肩部', '陆上', '拉伸'],
  },
  {
    id: 'drill-dryland-029',
    name: '髋部展开',
    nameZh: '髋部展开',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['髋部灵活性', '核心稳定性'],
    steps: ['站立', '前后劈叉', '缓慢展开', '保持15-30秒'],
    keyPoints: ['髋关节活动度', '前后劈叉', '急于求成'],
    commonErrors: [{ error: '急于求成', correction: '缓慢展开，不勉强' }],
    recommendedSets: '保持15-30秒，3-5次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['髋关节伤'],
    source: 'DrillBook 2E',
    tags: ['柔韧', '髋部', '陆上', '劈叉'],
  },
  {
    id: 'drill-dryland-030',
    name: '猫牛式伸展',
    nameZh: '猫牛式伸展',
    category: 'dryland',
    strokes: ['butterfly', 'breaststroke'],
    level: 'L1',
    purpose: ['髋部灵活性', '核心稳定性'],
    steps: ['四点支撑', '吸气抬头塌腰', '呼气低头拱背', '脊椎波浪'],
    keyPoints: ['脊椎活动', '脊椎波浪', '代偿'],
    commonErrors: [{ error: '代偿', correction: '用脊椎发力，不代偿' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: ['腰伤'],
    source: 'DrillBook 2E',
    tags: ['柔韧', '脊椎', '陆上', '波浪'],
  },

  // --- 8.5 反应与专项训练 ---
  
  {
    id: 'drill-dryland-031',
    name: '墙上起跳→流线型跳跃',
    nameZh: '墙上起跳流线型跳跃',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术', '核心稳定性'],
    steps: ['面对墙站立', '快速起跳', '流线型姿势', '模拟出发'],
    keyPoints: ['出发反应', '快速反应', '流线型'],
    commonErrors: [{ error: '反应慢', correction: '快速起跳，模拟出发' }],
    recommendedSets: '10-15次，3-5组',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '反应', '陆上', '跳跃'],
  },
  {
    id: 'drill-dryland-032',
    name: '出发台上反应出发训练',
    nameZh: '出发台反应训练',
    category: 'dryland',
    strokes: ['all'],
    level: 'L2',
    purpose: ['出发技术', '核心稳定性'],
    steps: ['站在出发台', '听信号', '快速反应出发', '模拟比赛'],
    keyPoints: ['反应时间', '专注听信号', '快速出发'],
    commonErrors: [{ error: '反应慢', correction: '专注听信号，快速反应' }],
    recommendedSets: '8-10次',
    recommendedZones: ['Z1'],
    progressions: [],
    contraindications: [],
    source: 'DrillBook 2E',
    tags: ['出发', '反应', '陆上', '信号'],
  },
  {
    id: 'drill-dryland-033',
    name: '药球投掷',
    nameZh: '药球投掷',
    category: 'dryland',
    strokes: ['all'],
    level: 'L3',
    purpose: ['核心稳定性'],
    steps: ['站立', '双手持药球', '用力投掷', '模拟划水发力'],
    keyPoints: ['爆发力', '与游泳发力方向相似', '用力投掷'],
    commonErrors: [{ error: '方向不对', correction: '模拟游泳发力方向投掷' }],
    recommendedSets: '10-15次每组，3-5组',
    recommendedZones: ['Z2'],
    progressions: [],
    contraindications: ['肩伤', '腰伤'],
    source: 'DrillBook 2E',
    tags: ['爆发', '药球', '陆上', '投掷'],
  },
];
