import type { ErrorPattern } from './types'

export const ERROR_REGISTRY: ErrorPattern[] = [
  {
    id: 'legs_sinking',
    nameZh: '腿部下沉',
    nameEn: 'Legs Sinking',
    stroke: 'Freestyle',
    category: 'Body Position',
    symptom: '游泳过程中腿部明显低于身体水平线，身体拖水感强。',
    rootCauses: ['头部位置过高', '核心稳定不足', '呼吸时抬头', '前伸与重心控制不足'],
    performanceImpact: ['增加阻力', '降低推进效率', '打乱配速稳定性'],
    correctionPrinciples: ['保持头部中立', '增强核心稳定', '通过前伸与胸口轻压前移重心'],
    recommendedDrills: ['Torpedo Kick', 'Tip Forward', 'Kick On Side'],
    relatedErrors: ['head_too_high', 'breathing_with_head_lift'],
    difficulty: 2,
  },
  {
    id: 'head_too_high',
    nameZh: '头部过高',
    nameEn: 'Head Too High',
    stroke: 'Freestyle',
    category: 'Body Position',
    symptom: '头位长期偏高，视线向前，导致臀腿下沉。',
    rootCauses: ['害怕入水', '换气习惯错误', '缺乏头位意识'],
    performanceImpact: ['前端阻力增加', '腿部下沉', '划水节奏被打断'],
    correctionPrinciples: ['视线看池底前下方', '保持颈部放松', '换气由滚转带动而非抬头'],
    recommendedDrills: ['Popeye Breathing', 'Tip Forward', 'Freestyle Side Glide with Breathing'],
    relatedErrors: ['legs_sinking', 'breathing_with_head_lift'],
    difficulty: 1,
  },
  {
    id: 'body_snaking',
    nameZh: '身体左右摇摆',
    nameEn: 'Body Snaking',
    stroke: 'Freestyle',
    category: 'Body Position',
    symptom: '身体在中线两侧明显左右晃动，前进路线不直。',
    rootCauses: ['交叉入水', '滚转控制差', '核心稳定不足'],
    performanceImpact: ['浪费推进力', '增加侧向阻力', '配速不稳定'],
    correctionPrinciples: ['保持中线控制', '入水落点在肩前', '髋肩协同滚转'],
    recommendedDrills: ['Broken Arrow Drill', 'Lateral Balance', '6-3-6 Drill'],
    relatedErrors: ['cross_over_entry', 'insufficient_rotation'],
    difficulty: 3,
  },
  {
    id: 'insufficient_rotation',
    nameZh: '身体滚动不足',
    nameEn: 'Insufficient Rotation',
    stroke: 'Freestyle',
    category: 'Body Position',
    symptom: '身体几乎平躺在水面上，换气与抓水都显得生硬。',
    rootCauses: ['髋部不参与', '怕失去平衡', '只用手臂发力'],
    performanceImpact: ['抓水浅', '换气困难', '恢复僵硬'],
    correctionPrinciples: ['由髋带动滚转', '建立侧身平衡', '让换气跟随滚转发生'],
    recommendedDrills: ['6-1-6 Drill', 'Kick On Side', 'Breathe from Hips'],
    relatedErrors: ['delayed_breath', 'dropped_elbow'],
    difficulty: 2,
  },
  {
    id: 'excessive_rotation',
    nameZh: '身体滚动过大',
    nameEn: 'Excessive Rotation',
    stroke: 'Freestyle',
    category: 'Body Position',
    symptom: '身体滚转过度，出现停顿、蛇形或换气失衡。',
    rootCauses: ['过度追求侧身', '换气时带动过大', '核心控制不足'],
    performanceImpact: ['线路不稳定', '划水发力延迟', '节奏被打断'],
    correctionPrinciples: ['控制滚转幅度', '保持髋肩同步', '以前进为核心而非过度侧身'],
    recommendedDrills: ['6-3-6 Drill', 'Power Zone', 'Freestyle Side Glide'],
    relatedErrors: ['body_snaking', 'breathing_with_head_lift'],
    difficulty: 3,
  },

  {
    id: 'holding_breath',
    nameZh: '憋气',
    nameEn: 'Holding Breath',
    stroke: 'Freestyle',
    category: 'Breathing',
    symptom: '水下不持续吐气，换气时明显慌乱或一次性猛吐猛吸。',
    rootCauses: ['水下呼气习惯差', '紧张', '换气节奏不固定'],
    performanceImpact: ['心率飙升', '动作僵硬', '耐力下降'],
    correctionPrinciples: ['建立持续吐气', '吸气短吐气长', '把呼吸节奏嵌入划水节奏'],
    recommendedDrills: ['Sink Down Exercise', 'Breathe-Bubble-Bubble-Breathe', 'Constant Breathing'],
    relatedErrors: ['delayed_breath', 'breathing_with_head_lift'],
    difficulty: 1,
  },
  {
    id: 'breathing_with_head_lift',
    nameZh: '过度抬头换气',
    nameEn: 'Breathing With Head Lift',
    stroke: 'Freestyle',
    category: 'Breathing',
    symptom: '换气时头部大幅抬出水面，两眼完全离水。',
    rootCauses: ['害怕喝水', '不会侧向换气', '身体滚转不足'],
    performanceImpact: ['腿部下沉', '阻力增加', '打断节奏'],
    correctionPrinciples: ['一眼在水中换气', '靠滚转完成呼吸', '保持前伸手稳定'],
    recommendedDrills: ['Popeye Breathing', 'Reach to Inhale', 'Freestyle Side Glide with Breathing'],
    relatedErrors: ['head_too_high', 'legs_sinking'],
    difficulty: 2,
  },
  {
    id: 'delayed_breath',
    nameZh: '换气延迟',
    nameEn: 'Delayed Breath',
    stroke: 'Freestyle',
    category: 'Breathing',
    symptom: '换气发生在划水后半程甚至过晚，导致抢气与动作变形。',
    rootCauses: ['节奏感不足', '滚转启动太晚', '水下吐气不充分'],
    performanceImpact: ['节奏断裂', '换气慌乱', '划水路径变形'],
    correctionPrinciples: ['提前准备换气', '让滚转与呼吸同步', '减少水下憋气'],
    recommendedDrills: ['Breathe-Bubble-Bubble-Breathe', 'Reach to Inhale', '6-1-6 Drill'],
    relatedErrors: ['holding_breath', 'single_side_breathing_dependency'],
    difficulty: 2,
  },
  {
    id: 'single_side_breathing_dependency',
    nameZh: '单侧换气依赖',
    nameEn: 'Single-Side Breathing Dependency',
    stroke: 'Freestyle',
    category: 'Breathing',
    symptom: '只能向单侧换气，另一侧明显不稳定或无法完成。',
    rootCauses: ['侧向平衡不足', '呼吸心理偏好', '双侧节奏训练不足'],
    performanceImpact: ['比赛与开放水域适应性差', '动作不对称', '身体容易偏移'],
    correctionPrinciples: ['从低强度建立双侧换气', '提高非优势侧平衡', '先练节奏再提强度'],
    recommendedDrills: ['Freestyle Side Glide with Breathing', 'Constant Breathing', '6-3-6 Drill'],
    relatedErrors: ['body_snaking', 'delayed_breath'],
    difficulty: 3,
  },

  {
    id: 'pressing_down_early',
    nameZh: '提前压水',
    nameEn: 'Pressing Down Early',
    stroke: 'Freestyle',
    category: 'Catch',
    symptom: '手入水后立刻向下压水，前臂无法形成有效抓水面。',
    rootCauses: ['抓水概念错误', '肩部紧张', '想用向下压来抬头或换气'],
    performanceImpact: ['前进方向错误', '阻力增加', '抓水效率低'],
    correctionPrinciples: ['先前伸再立前臂', '让前臂参与抱水', '保持肩部放松稳定'],
    recommendedDrills: ['Sculling Drills', 'Over the Barrel', 'Broken Arrow Drill'],
    relatedErrors: ['dropped_elbow', 'head_too_high'],
    difficulty: 3,
  },
  {
    id: 'dropped_elbow',
    nameZh: '肘部下沉',
    nameEn: 'Dropped Elbow',
    stroke: 'Freestyle',
    category: 'Catch',
    symptom: '抓水阶段肘部位置过低，前臂无法形成高效受力面。',
    rootCauses: ['肩胛控制差', '高肘概念不足', '急于用手下压'],
    performanceImpact: ['抓水浅', '推进效率低', '肩部压力增加'],
    correctionPrinciples: ['保持相对高肘', '前臂尽早参与受力', '用抱水替代压水'],
    recommendedDrills: ['Sculling Drills', 'Over the Barrel', 'Shark Fin Drill'],
    relatedErrors: ['pressing_down_early', 'incomplete_push'],
    difficulty: 3,
  },
  {
    id: 'cross_over_entry',
    nameZh: '交叉入水',
    nameEn: 'Cross-Over Entry',
    stroke: 'Freestyle',
    category: 'Recovery',
    symptom: '手入水点越过身体中线，导致身体扭曲和蛇形前进。',
    rootCauses: ['恢复路径外摆后内扣', '中线感差', '肩部与核心控制差'],
    performanceImpact: ['身体左右摇摆', '抓水角度差', '肩部压力增加'],
    correctionPrinciples: ['入水点保持在肩前', '恢复贴近身体中线但不过线', '保持躯干稳定'],
    recommendedDrills: ['Fingertip Drag', 'Zipper Drill', 'Broken Arrow Drill'],
    relatedErrors: ['body_snaking', 'stroke_path_too_wide'],
    difficulty: 2,
  },
  {
    id: 'incomplete_push',
    nameZh: '推水不完整',
    nameEn: 'Incomplete Push',
    stroke: 'Freestyle',
    category: 'Pull',
    symptom: '划水后段提前出水，缺少完整后推。',
    rootCauses: ['后程发力意识弱', '节奏过急', '疲劳后动作缩短'],
    performanceImpact: ['推进距离缩短', '配速效率下降', '划频被迫异常升高'],
    correctionPrinciples: ['完成后推到髋旁', '保持末端加速', '让每次划水推进更完整'],
    recommendedDrills: ['Pocket Drill', 'Accelerate Arm Stroke', 'Popov Drill'],
    relatedErrors: ['stroke_path_too_narrow', 'dropped_elbow'],
    difficulty: 2,
  },
  {
    id: 'stroke_path_too_wide',
    nameZh: '划水路径过宽',
    nameEn: 'Stroke Path Too Wide',
    stroke: 'Freestyle',
    category: 'Pull',
    symptom: '划水路线向身体外侧偏移明显，推进方向分散。',
    rootCauses: ['交叉入水后的补偿', '中线意识差', '躯干稳定不足'],
    performanceImpact: ['横向力浪费', '推进不直', '节奏不稳定'],
    correctionPrinciples: ['让划水更贴合推进方向', '建立中线控制', '抓水后向后推进而非向外扫'],
    recommendedDrills: ['Broken Arrow Drill', 'Sculling Drills', '3D Freestyle'],
    relatedErrors: ['cross_over_entry', 'body_snaking'],
    difficulty: 3,
  },
  {
    id: 'stroke_path_too_narrow',
    nameZh: '划水路径过窄',
    nameEn: 'Stroke Path Too Narrow',
    stroke: 'Freestyle',
    category: 'Pull',
    symptom: '划水路线过于贴中线或过分向身体下方收，影响受力面积。',
    rootCauses: ['过度追求贴中线', '抓水深度不合理', '肩肘协调差'],
    performanceImpact: ['抓水面积不足', '发力别扭', '肩部压力增加'],
    correctionPrinciples: ['保持自然抓水宽度', '建立稳定受力面', '避免过度内扣'],
    recommendedDrills: ['Sculling Drills', 'Over the Barrel', '3D Freestyle'],
    relatedErrors: ['stroke_path_too_wide', 'dropped_elbow'],
    difficulty: 3,
  },

  {
    id: 'excessive_knee_bend',
    nameZh: '屈膝过大',
    nameEn: 'Excessive Knee Bend',
    stroke: 'Freestyle',
    category: 'Kick',
    symptom: '打腿时膝关节屈伸明显，像骑自行车一样踢水。',
    rootCauses: ['不会从髋发力', '踝关节僵硬', '腿部节奏感不足'],
    performanceImpact: ['阻力变大', '推进效率低', '腿部疲劳快'],
    correctionPrinciples: ['从髋部带动打腿', '保持腿长而松', '减小踢腿幅度'],
    recommendedDrills: ['Fish Don\'t Have Knees', 'Ballet Leg Kick Drill', 'Kick the Ball'],
    relatedErrors: ['kick_from_knees', 'ankle_stiffness'],
    difficulty: 1,
  },
  {
    id: 'kick_frequency_too_low',
    nameZh: '打腿频率过低',
    nameEn: 'Kick Frequency Too Low',
    stroke: 'Freestyle',
    category: 'Kick',
    symptom: '腿部节奏太慢，无法支撑身体线条与节奏需求。',
    rootCauses: ['腿部耐力不足', '缺乏节奏感', '只关注手臂不关注腿'],
    performanceImpact: ['身体线条差', '速度不足', '换气不稳定'],
    correctionPrinciples: ['建立小幅快频', '根据项目匹配 2-beat 或 6-beat 节奏', '让腿与手协同'],
    recommendedDrills: ['Kick the Ball', 'Six-Beat Kick', 'Vertical Flutter Kick'],
    relatedErrors: ['legs_sinking', 'hands_feet_out_of_sync'],
    difficulty: 2,
  },
  {
    id: 'kick_from_knees',
    nameZh: '打腿来自膝关节',
    nameEn: 'Kick From Knees',
    stroke: 'Freestyle',
    category: 'Kick',
    symptom: '打腿主要由膝盖驱动，而不是从髋部发起。',
    rootCauses: ['髋部发力概念不清', '腿部放松不足', '打腿动作模式错误'],
    performanceImpact: ['推进效率低', '膝部负担增加', '身体线条被破坏'],
    correctionPrinciples: ['从髋带动整条腿', '保持膝部自然微弯', '小幅连续打腿'],
    recommendedDrills: ['Fish Don\'t Have Knees', 'Streamline Freestyle Kick', 'Ballet Leg Kick Drill'],
    relatedErrors: ['excessive_knee_bend', 'ankle_stiffness'],
    difficulty: 1,
  },
  {
    id: 'ankle_stiffness',
    nameZh: '脚踝僵硬',
    nameEn: 'Ankle Stiffness',
    stroke: 'Freestyle',
    category: 'Kick',
    symptom: '脚背绷不起来，踝关节活动度不足，打腿像“拍水”。',
    rootCauses: ['踝关节活动度不足', '打腿紧张', '缺乏踝部放松训练'],
    performanceImpact: ['推进效率低', '腿部耗能高', '节奏感差'],
    correctionPrinciples: ['提升踝活动度', '脚背自然绷直', '保持腿部放松'],
    recommendedDrills: ['Ballet Leg Kick Drill', 'Streamline Freestyle Kick', 'Vertical Flutter Kick'],
    relatedErrors: ['kick_from_knees', 'excessive_knee_bend'],
    difficulty: 2,
  },

  {
    id: 'hands_feet_out_of_sync',
    nameZh: '手脚不同步',
    nameEn: 'Hands and Feet Out of Sync',
    stroke: 'Freestyle',
    category: 'Coordination',
    symptom: '手臂划水与打腿节奏脱节，整体动作断裂或节奏混乱。',
    rootCauses: ['节奏概念不清', '只关注单一部位', '配合练习不足'],
    performanceImpact: ['动作不连贯', '推进效率低', '配速控制差'],
    correctionPrinciples: ['建立固定打腿配合模式', '先低强度练节奏再提速', '让滚转/呼吸/打腿同步'],
    recommendedDrills: ['6-1-6 Drill', '6-3-6 Drill', 'Two-Beat Kick'],
    relatedErrors: ['kick_frequency_too_low', 'single_side_breathing_dependency'],
    difficulty: 3,
  },
]

